### ISSUE TITLE
Mac 12.4, M1, CPU only, run grounded_sam_inpainting_demo.py, error: LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by distort5871** [IDEA-Research/Grounded-Segment-Anything#104]
when i run on my mac laptop, i got following error:

## my command
```bash
python grounded_sam_inpainting_demo.py   --config GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py   --grounded_checkpoint groundingdino_swint_ogc.pth   --sam_checkpoint sam_vit_h_4b8939.pth   --input_image assets/inpaint_demo.jpg   --output_dir "outputs"   --box_threshold 0.3   --text_threshold 0.25   --det_prompt "bench"   --inpaint_prompt "A sofa, high quality, detailed"   --device "cpu"
```
**note that option with --device "cpu"**
## error
```sql
Traceback (most recent call last):
  File "grounded_sam_inpainting_demo.py", line 203, in <module>
    image = pipe(prompt=inpaint_prompt, image=image_pil, mask_image=mask_pil).images[0]
  File "/Users//miniconda3/envs/gsa/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users//miniconda3/envs/gsa/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py", line 787, in __call__
    prompt_embeds = self._encode_prompt(
  File "/Users//miniconda3/envs/gsa/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py", line 402, in _encode_prompt
    prompt_embeds = self.text_encoder(
  File "/Users//miniconda3/envs/gsa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users//miniconda3/envs/gsa/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 816, in forward
    return self.text_model(
  File "/Users//miniconda3/envs/gsa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users//miniconda3/envs/gsa/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 725, in forward
    encoder_outputs = self.encoder(
  File "/Users//miniconda3/envs/gsa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users//miniconda3/envs/gsa/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 654, in forward
    layer_outputs = encoder_layer(
  File "/Users//miniconda3/envs/gsa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users//miniconda3/envs/gsa/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 382, in forward
    hidden_states = self.layer_norm1(hidden_states)
  File "/Users//miniconda3/envs/gsa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users//miniconda3/envs/gsa/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 190, in forward
    return F.layer_norm(
  File "/Users//miniconda3/envs/gsa/lib/python3.8/site-packages/torch/nn/functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
```
## what i do
when i first run command, it give me error about gpu, and i find the point is here:
```sql
vim grounded_sam_inpainting_demo.py
```
so i change the code from:
```python
197    pipe = pipe.to("cuda")
```
to 
```python
197     # pipe = pipe.to("cuda")
198     pipe = pipe.to("cpu")
```
after doing that, i run the top command again, and i got the top error.

** so  anybody can give some advice about this problem, or give some information about how to run the model on my laptop with no CPU only**

**Comment by lukew244** [comment]
@SlongLiu's solution solved this for me, thanks.

**Comment by distort5871** [comment]
> Can you have a try that modify the `float16` to `float32` in https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/main/grounded_sam_inpainting_demo.py#L194
> 
> ```python
>     pipe = StableDiffusionInpaintPipeline.from_pretrained(
>     "runwayml/stable-diffusion-inpainting", torch_dtype=torch.float16 # to float32
>     )
> ```

it works for me, thanks.
