### ISSUE TITLE
Is it possible to batch inputs?

### ISSUE THREAD

**Issue by WangYixuan12** [IDEA-Research/Grounded-Segment-Anything#117]
The inference is currently performed on a single image and single text prompts. Is it possible to batch inputs (images or text prompts)?

**Comment by SlongLiu** [comment]
Thanks for your suggestions. We will update batch inputs later. 

For now, you can modify the inputs in demo codes to enable batch inputs.

**Comment by imandrealombardo** [comment]
+1!

**Comment by alelordelo** [comment]
+1

Anyone managed to get batch working? What is the recommend batch size on an A100 GPU with 1024 x 768 images?

**Comment by ChengFengGu** [comment]
+1

**Comment by KaKituken** [comment]
The model supports batched prediction inherently, you just need to modify the `predict` function in `groundingdino.util.inference`.

The key point is to modify this line:
```python
with torch.no_grad():
        outputs = model(image[None], captions=[caption])
```
We can tell from here the first dim of input image & captions is actually `batch size`. Therefore, the only thing we need to do is using `torch.stack` to stack our batched input, besides do some change in the post process.

The batched input version could be
```python
import groundingdino.datasets.transforms as T
from groundingdino.models import build_model
from groundingdino.util import box_ops
from groundingdino.util.slconfig import SLConfig
from groundingdino.util.utils import clean_state_dict, get_phrases_from_posmap
from groundingdino.util.inference import load_image

# detect object using grounding DINO
def detect(images_list, text_prompts, model, box_threshold = 0.3, text_threshold = 0.25, device='cuda'):

    captions = [preprocess_caption(caption) for caption in text_prompts]

    images = torch.stack(images_list)
    images = images.to(device)

    with torch.no_grad():
        outputs = model(images, captions=captions)

    prediction_logits = outputs["pred_logits"].cpu().sigmoid()  # prediction_logits.shape = (bsz，nq, 256)
    prediction_boxes = outputs["pred_boxes"].cpu()  # prediction_boxes.shape = (bsz, nq, 4)

    logits_res = []
    boxs_res = []
    phrases_list = []
    tokenizer = model.tokenizer
    for ub_logits, ub_boxes, ub_captions in zip(prediction_logits, prediction_boxes, captions):
        mask = ub_logits.max(dim=1)[0] > box_threshold
        logits = ub_logits[mask]  # logits.shape = (n, 256)
        boxes = ub_boxes[mask]  # boxes.shape = (n, 4)
        logits_res.append(logits.max(dim=1)[0])
        boxs_res.append(boxes)

        tokenized = tokenizer(ub_captions)
        phrases = [
            get_phrases_from_posmap(logit > text_threshold, tokenized, tokenizer).replace('.', '')
            for logit
            in logits
        ]
        phrases_list.append(phrases)
    print('bboxs:', boxs_res)
    print('logits:', logits_res)
    print('phrases:', phrases_list)
    return boxs_res, logits_res, phrases_list
```
You can find the additional two accessorial functions `load_model_hf` and `preprocess_caption` in the [online demo]( https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/main/grounded_sam_colab_demo.ipynb) and `groundingdino.util.inference` respectively.

**Comment by KevinZ-01** [comment]
> The model supports batched prediction inherently, you just need to modify the `predict` function in `groundingdino.util.inference`.
> 
> The key point is to modify this line:
> 
> ```python
> with torch.no_grad():
>         outputs = model(image[None], captions=[caption])
> ```
> 
> We can tell from here the first dim of input image & captions is actually `batch size`. Therefore, the only thing we need to do is using `torch.stack` to stack our batched input, besides do some change in the post process.
> 
> The batched input version could be
> 
> ```python
> import groundingdino.datasets.transforms as T
> from groundingdino.models import build_model
> from groundingdino.util import box_ops
> from groundingdino.util.slconfig import SLConfig
> from groundingdino.util.utils import clean_state_dict, get_phrases_from_posmap
> from groundingdino.util.inference import load_image
> 
> # detect object using grounding DINO
> def detect(images_list, text_prompts, model, box_threshold = 0.3, text_threshold = 0.25, device='cuda'):
> 
>     captions = [preprocess_caption(caption) for caption in text_prompts]
> 
>     images = torch.stack(images_list)
>     images = images.to(device)
> 
>     with torch.no_grad():
>         outputs = model(images, captions=captions)
> 
>     prediction_logits = outputs["pred_logits"].cpu().sigmoid()  # prediction_logits.shape = (bsz，nq, 256)
>     prediction_boxes = outputs["pred_boxes"].cpu()  # prediction_boxes.shape = (bsz, nq, 4)
> 
>     logits_res = []
>     boxs_res = []
>     phrases_list = []
>     tokenizer = model.tokenizer
>     for ub_logits, ub_boxes, ub_captions in zip(prediction_logits, prediction_boxes, captions):
>         mask = ub_logits.max(dim=1)[0] > box_threshold
>         logits = ub_logits[mask]  # logits.shape = (n, 256)
>         boxes = ub_boxes[mask]  # boxes.shape = (n, 4)
>         logits_res.append(logits.max(dim=1)[0])
>         boxs_res.append(boxes)
> 
>         tokenized = tokenizer(ub_captions)
>         phrases = [
>             get_phrases_from_posmap(logit > text_threshold, tokenized, tokenizer).replace('.', '')
>             for logit
>             in logits
>         ]
>         phrases_list.append(phrases)
>     print('bboxs:', boxs_res)
>     print('logits:', logits_res)
>     print('phrases:', phrases_list)
>     return boxs_res, logits_res, phrases_list
> ```
> 
> You can find the additional two accessorial functions `load_model_hf` and `preprocess_caption` in the [online demo](https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/main/grounded_sam_colab_demo.ipynb) and `groundingdino.util.inference` respectively.

Interesting! I used this method, but I found the inference speed is not getting much faster. e.g. using batch size 32 tooks ~6 seconds, which is similar to inference one by one. Any idea on this? Thanks!

**Comment by GuoPingPan** [comment]
But I got an error as below.
```
Original exception was:
Traceback (most recent call last):
  File "/home/a4090/lfwh/WiLoR/scripts/tracking_offline_collection_batch.py", line 378, in <module>
    queries = fastsam_mask(fastsam_model, gd_model, init_img, text=text)
  File "/home/a4090/lfwh/WiLoR/scripts/tracking_offline_collection_batch.py", line 90, in fastsam_mask
    boxes, logits, phrases = predict(
  File "/home/a4090/lfwh/Grounded-Segment-Anything/GroundingDINO/groundingdino/util/inference.py", line 70, in predict
    outputs = model(image, captions=caption)
  File "/home/a4090/miniconda3/envs/wilor/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/a4090/miniconda3/envs/wilor/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/a4090/lfwh/Grounded-Segment-Anything/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 243, in forward
    ) = generate_masks_with_special_tokens_and_transfer_map(
  File "/home/a4090/lfwh/Grounded-Segment-Anything/GroundingDINO/groundingdino/models/GroundingDINO/bertwarper.py", line 265, in generate_masks_with_special_tokens_and_transfer_map
    cate_to_token_mask_list = [
  File "/home/a4090/lfwh/Grounded-Segment-Anything/GroundingDINO/groundingdino/models/GroundingDINO/bertwarper.py", line 266, in <listcomp>
    torch.stack(cate_to_token_mask_listi, dim=0)
RuntimeError: stack expects a non-empty TensorList
```

**Comment by ZhaoChuyang** [comment]
> But I got an error as below.
> 
> ```
> Original exception was:
> Traceback (most recent call last):
>   File "/home/a4090/lfwh/WiLoR/scripts/tracking_offline_collection_batch.py", line 378, in <module>
>     queries = fastsam_mask(fastsam_model, gd_model, init_img, text=text)
>   File "/home/a4090/lfwh/WiLoR/scripts/tracking_offline_collection_batch.py", line 90, in fastsam_mask
>     boxes, logits, phrases = predict(
>   File "/home/a4090/lfwh/Grounded-Segment-Anything/GroundingDINO/groundingdino/util/inference.py", line 70, in predict
>     outputs = model(image, captions=caption)
>   File "/home/a4090/miniconda3/envs/wilor/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/a4090/miniconda3/envs/wilor/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/a4090/lfwh/Grounded-Segment-Anything/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 243, in forward
>     ) = generate_masks_with_special_tokens_and_transfer_map(
>   File "/home/a4090/lfwh/Grounded-Segment-Anything/GroundingDINO/groundingdino/models/GroundingDINO/bertwarper.py", line 265, in generate_masks_with_special_tokens_and_transfer_map
>     cate_to_token_mask_list = [
>   File "/home/a4090/lfwh/Grounded-Segment-Anything/GroundingDINO/groundingdino/models/GroundingDINO/bertwarper.py", line 266, in <listcomp>
>     torch.stack(cate_to_token_mask_listi, dim=0)
> RuntimeError: stack expects a non-empty TensorList
> ```

```python
def generate_masks_with_special_tokens_and_transfer_map(tokenized, special_tokens_list, tokenizer):
    """Generate attention mask between each pair of special tokens
    Args:
        input_ids (torch.Tensor): input ids. Shape: [bs, num_token]
        special_tokens_mask (list): special tokens mask.
    Returns:
        torch.Tensor: attention mask between each special tokens.
    """
    input_ids = tokenized["input_ids"]
    bs, num_token = input_ids.shape
    # special_tokens_mask: bs, num_token. 1 for special tokens. 0 for normal tokens
    special_tokens_mask = torch.zeros((bs, num_token), device=input_ids.device).bool()
    for special_token in special_tokens_list:
        special_tokens_mask |= input_ids == special_token

    # idxs: each row is a list of indices of special tokens
    idxs = torch.nonzero(special_tokens_mask)

    # generate attention mask and positional ids
    attention_mask = (
        torch.eye(num_token, device=input_ids.device).bool().unsqueeze(0).repeat(bs, 1, 1)
    )
    position_ids = torch.zeros((bs, num_token), device=input_ids.device)
    cate_to_token_mask_list = [[] for _ in range(bs)]
    previous_col = 0
    for i in range(idxs.shape[0]):
        row, col = idxs[i]
        if (col == 0) or (col == num_token - 1):
        # if (col == 0):
            attention_mask[row, col, col] = True
            position_ids[row, col] = 0
        else:
            attention_mask[row, previous_col + 1 : col + 1, previous_col + 1 : col + 1] = True
            position_ids[row, previous_col + 1 : col + 1] = torch.arange(
                0, col - previous_col, device=input_ids.device
            )
            c2t_maski = torch.zeros((num_token), device=input_ids.device).bool()
            c2t_maski[previous_col + 1 : col] = True
            cate_to_token_mask_list[row].append(c2t_maski)
        # Handle the last special token case
        if col == num_token - 1:
            c2t_maski = torch.zeros((num_token), device=input_ids.device).bool()
            c2t_maski[previous_col + 1 : col] = True
            cate_to_token_mask_list[row].append(c2t_maski)
        previous_col = col

    cate_to_token_mask_list = [
        torch.stack(cate_to_token_mask_listi, dim=0)
        for cate_to_token_mask_listi in cate_to_token_mask_list
    ]

    # # padding mask
    # padding_mask = tokenized['attention_mask']
    # attention_mask = attention_mask & padding_mask.unsqueeze(1).bool() & padding_mask.unsqueeze(2).bool()

    return attention_mask, position_ids.to(torch.long), cate_to_token_mask_list
```

I fixed it by modify `generate_masks_with_special_tokens_and_transfer_map`, seems bug in processing attention mask
