### ISSUE TITLE
python -m pip install -e GroundingDINO 报错

### ISSUE THREAD

**Issue by mls2009** [IDEA-Research/Grounded-Segment-Anything#173]
Obtaining file:///F:/AI/Grounded-Segment-Anything/GroundingDINO
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [9 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "F:\AI\Grounded-Segment-Anything\GroundingDINO\setup.py", line 214, in <module>
      ext_modules=get_extensions(),
    File "F:\AI\Grounded-Segment-Anything\GroundingDINO\setup.py", line 72, in get_extensions
      am_i_docker = os.environ.get('AM_I_DOCKER').casefold() in ['true', '1', 't']
  AttributeError: 'NoneType' object has no attribute 'casefold'
  Building wheel groundingdino-0.1.0
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by fengyueyeah** [comment]
Encountered the same bug

**Comment by rentainhe** [comment]
Sorry for this issue， you can set the environment env as follows if you are not using docker env:

```bash
export AM_I_DOCKER=False
export BUILD_WITH_CUDA=True
```

Then running the installation

```bash
python -m pip install -e GroundingDINO
```

**Comment by gukehan2000** [comment]
cuda路径你得自己改 他那个只是提示你改称cuda11.3路径
