### ISSUE TITLE
questions on VISAM: how to fill --mot_path your_data_path?

### ISSUE THREAD

**Issue by aixiaodewugege** [IDEA-Research/Grounded-Segment-Anything#179]
Can you provide a more specific guide on how to reproduce your demo with VISAM?

**Comment by fengxiuyaun** [comment]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/6481257/233345936-058a33ea-5c4d-4cc3-b653-01b5f2b9e37d.png">
for example, --mot_path=/data/Dataset/mot

**Comment by aixiaodewugege** [comment]
Thanks for your quick reply. But I think that it failed to load the config file, even if I use your settings. Did I miss anything?

Here is my error log:

(mmedit-sam) wushuchen@wushuchen:~/projects/SAM_test/Grounded-Segment-Anything$ python grounded_sam_visam.py   --meta_arch motr   --dataset_file e2e_dance   --with_box_refine   --query_interaction_layer QIMv2   --num_queries 10   --det_db det_db_motrv2.json   --use_checkpoint   --mot_path ./   --resume motrv2_dancetrack.pth   --sam_checkpoint sam_vit_h_4b8939.pth   --video_path DanceTrack/test/dancetrack0003 


/home/wushuchen/anaconda3/envs/mmedit-sam/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/home/wushuchen/anaconda3/envs/mmedit-sam/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Training with Self-Cross Attention.
None aaaaaaaaaaaaaaaaaaaaa
Traceback (most recent call last):
  File "grounded_sam_visam.py", line 253, in <module>
    detr, _, _ = build_model(args)
  File "/home/wushuchen/projects/SAM_test/Grounded-Segment-Anything/VISAM/models/__init__.py", line 19, in build_model
    return build_func(args)
  File "/home/wushuchen/projects/SAM_test/Grounded-Segment-Anything/VISAM/models/motr.py", line 731, in build
    num_frames_per_batch = max(args.sampler_lengths)
TypeError: 'NoneType' object is not iterable

And my folder structed is as followed:
![image](https://user-images.githubusercontent.com/47085237/233358222-44fba69b-cfd5-4327-8edf-4ab201c8642d.png)

**Comment by fengxiuyaun** [comment]
Sorry, you can use this param" --meta_arch motr --dataset_file e2e_dance --with_box_refine --batch_size 1 --sample_mode random_interval --sample_interval 10 --sampler_lengths 5 --merger_dropout 0 --dropout 0 --random_drop 0.1 --fp_ratio 0.3 --query_interaction_layer QIMv2 --query_denoise 0.05 --num_queries 10 --append_crowd --det_db det_db_motrv2.json --use_checkpoint --mot_path XXX --resume motrv2_dancetrack.pth --sam_checkpoint sam_vit_h_4b8939.pth --video_path DanceTrack/test/dancetrack0003"， I will change readme

**Comment by dcjniwota** [comment]
I have the same problem:TypeError: 'NoneType' object is not iterable，thank you for your replay. Other question is: what's in e2e_dance  dir?

**Comment by aixiaodewugege** [comment]
> I have the same problem:TypeError: 'NoneType' object is not iterable，thank you for your replay. Other question is: what's in e2e_dance dir?

I think it is not a dir, it means only detect people.

**Comment by aixiaodewugege** [comment]
Ok. Thanks.

Thank you for your work, it's wonderful !

**Comment by dcjniwota** [comment]
Here is my error new log when using the new command:
![image](https://user-images.githubusercontent.com/13598652/233537702-d36aa57d-ea9e-44aa-bc90-ef0cd286b66a.png)
All test image data In /vdb1/dataset/visam/mot/DanceTrack/test/dancetrack0003/img1:
![image](https://user-images.githubusercontent.com/13598652/233537897-d518a56d-b378-4d5a-acdf-9e4be00573c2.png)
Looking forward to your reply~

**Comment by fengxiuyaun** [comment]
xxx.txt in  --det_db det_db_motrv2.json. You can open  det_db_motrv2.json, then you will see it

**Comment by fengxiuyaun** [comment]
<img width="407" alt="image" src="https://user-images.githubusercontent.com/6481257/233541534-977307cb-33b8-4dbe-bc27-c1df001a0355.png">
here. you need to delete “/vdb1/dataset/visam/mot/”

**Comment by dcjniwota** [comment]
Thanks for your guidance, I have got the final result: "visam.avi"file~ The end result is different from the VISAM in README.md.

**Comment by fengxiuyaun** [comment]
Sure, I'm using my own weights. Looking forward to our future code.

**Comment by shixiaotong123** [comment]
i just want to use demo to test my own video, so why should i download the dataset into data folder

**Comment by arose26** [comment]
So... did anyone actually get this to run? And on their own video file?

**Comment by 2018141043089** [comment]
Can anybody tell me where is det_db_motrv2.json

**Comment by fengxiuyaun** [comment]
> det_db_motrv2.json

这个不需要。假如真的想用，可以参考MOTRv2
