### ISSUE TITLE
about buffer when running chatbot.py

### ISSUE THREAD

**Issue by tlx112233** [IDEA-Research/Grounded-Segment-Anything#181]
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\torch\lib\site-packages\gradio\routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\ProgramData\Anaconda3\envs\torch\lib\site-packages\gradio\blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "D:\ProgramData\Anaconda3\envs\torch\lib\site-packages\gradio\blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\ProgramData\Anaconda3\envs\torch\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\ProgramData\Anaconda3\envs\torch\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\ProgramData\Anaconda3\envs\torch\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Windows 10\Desktop\Grounded-Segment-Anything-main\chatbot.py", line 1307, in run_text
    self.agent.memory.buffer = cut_dialogue_history(self.agent.memory.buffer, keep_last_n_words=500)
  File "pydantic\main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "ConversationBufferMemory" object has no field "buffer"

who can help me explain about it?

**Comment by Andy1621** [comment]
see issue https://github.com/microsoft/TaskMatrix/issues/179#issuecomment-1467402903 , check your version of langchain.

**Comment by tlx112233** [comment]
it worked,thank you.

**Comment by 1119736939** [comment]
Thank you, it worked
