### ISSUE TITLE
Failed building wheel for pycocotools

### ISSUE THREAD

**Issue by 15704080** [IDEA-Research/Grounded-Segment-Anything#197]
Installing sd-webui-segment-anything requirement: groundingdino
提示：SD-WebUI 正在联网同步内部组件，这可能需要几秒到几十分钟不等，请耐心等待，切勿中途退出，以免文件损坏。切换版本后在此挂起一段时间是正常情况，如果您在使用中反复需要在此处等待 5 分钟以上，这可能是由于您安装的扩展与主环境产生版本冲突。请尝试通过扩展管理工具手动对齐扩展版本，或停用可疑扩展。
详见: https://support.qq.com/products/488228/faqs/135024
Traceback (most recent call last):
  File "D:\stablediffusion\.A1SDWEBUI\extensions\sd-webui-segment-anything\scripts\dino.py", line 36, in install_goundingdino
    launch.run_pip(
  File "D:\stablediffusion\.A1SDWEBUI\launch.py", line 129, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "D:\stablediffusion\.A1SDWEBUI\launch.py", line 97, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install sd-webui-segment-anything requirement: groundingdino.
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Command: "D:\stablediffusion\.A1SDWEBUI\py310\python.exe" -m pip install git+https://github.com/IDEA-Research/GroundingDINO --prefer-binary --index-url https://mirrors.bfsu.edu.cn/pypi/web/simple
Error code: 1
stdout: Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple, https://pypi.tuna.tsinghua.edu.cn/simple, https://pypi.doubanio.com/simple

Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html

Collecting git+https://github.com/IDEA-Research/GroundingDINO

  Cloning https://github.com/IDEA-Research/GroundingDINO to c:\users\dell\appdata\local\temp\pip-req-build-h4b7ea9k

  Resolved https://github.com/IDEA-Research/GroundingDINO to commit da9f1c0751935e9284890572069f4b2fef4cbfdc

  Preparing metadata (setup.py): started

  Preparing metadata (setup.py): finished with status 'done'

Requirement already satisfied: torch in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from groundingdino==0.1.0) (2.0.0+cu118)

Requirement already satisfied: torchvision in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from groundingdino==0.1.0) (0.15.1+cu118)

Requirement already satisfied: transformers in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from groundingdino==0.1.0) (4.25.1)

Requirement already satisfied: addict in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from groundingdino==0.1.0) (2.4.0)

Requirement already satisfied: yapf in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from groundingdino==0.1.0) (0.32.0)

Requirement already satisfied: timm in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from groundingdino==0.1.0) (0.6.7)

Requirement already satisfied: numpy in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from groundingdino==0.1.0) (1.23.3)

Requirement already satisfied: opencv-python in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from groundingdino==0.1.0) (4.6.0.66)

Collecting supervision==0.6.0

  Downloading https://pypi.doubanio.com/packages/42/7a/4fe657cae29eedeca34756a80a053ac3b1b3c80462cdb6768f428625f9ca/supervision-0.6.0-py3-none-any.whl (31 kB)

Collecting pycocotools

  Using cached https://pypi.doubanio.com/packages/ef/c6/90220be3b39fbc4cbd203775ca47dd8dc97fae06fbd2b500637395621b7c/pycocotools-2.0.6.tar.gz (24 kB)

  Installing build dependencies: started

  Installing build dependencies: finished with status 'done'

  Getting requirements to build wheel: started

  Getting requirements to build wheel: finished with status 'done'

  Preparing metadata (pyproject.toml): started

  Preparing metadata (pyproject.toml): finished with status 'done'

Requirement already satisfied: matplotlib in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from supervision==0.6.0->groundingdino==0.1.0) (3.6.2)

Requirement already satisfied: jinja2 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from torch->groundingdino==0.1.0) (3.1.2)

Requirement already satisfied: filelock in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from torch->groundingdino==0.1.0) (3.11.0)

Requirement already satisfied: networkx in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from torch->groundingdino==0.1.0) (3.1)

Requirement already satisfied: sympy in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from torch->groundingdino==0.1.0) (1.11.1)

Requirement already satisfied: typing-extensions in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from torch->groundingdino==0.1.0) (4.5.0)

Requirement already satisfied: requests in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from torchvision->groundingdino==0.1.0) (2.25.1)

Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from torchvision->groundingdino==0.1.0) (9.4.0)

Requirement already satisfied: packaging>=20.0 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from transformers->groundingdino==0.1.0) (21.3)

Requirement already satisfied: huggingface-hub<1.0,>=0.10.0 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from transformers->groundingdino==0.1.0) (0.13.4)

Requirement already satisfied: regex!=2019.12.17 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from transformers->groundingdino==0.1.0) (2022.10.31)

Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from transformers->groundingdino==0.1.0) (0.12.1)

Requirement already satisfied: pyyaml>=5.1 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from transformers->groundingdino==0.1.0) (6.0)

Requirement already satisfied: tqdm>=4.27 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from transformers->groundingdino==0.1.0) (4.64.1)

Requirement already satisfied: kiwisolver>=1.0.1 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (1.4.4)

Requirement already satisfied: fonttools>=4.22.0 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (4.38.0)

Requirement already satisfied: contourpy>=1.0.1 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (1.0.6)

Requirement already satisfied: python-dateutil>=2.7 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (2.8.2)

Requirement already satisfied: pyparsing>=2.2.1 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (3.0.9)

Requirement already satisfied: cycler>=0.10 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (0.11.0)

Requirement already satisfied: colorama in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from tqdm>=4.27->transformers->groundingdino==0.1.0) (0.4.6)

Requirement already satisfied: MarkupSafe>=2.0 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from jinja2->torch->groundingdino==0.1.0) (2.1.2)

Requirement already satisfied: chardet<5,>=3.0.2 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (4.0.0)

Requirement already satisfied: certifi>=2017.4.17 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (2022.12.7)

Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (1.26.15)

Requirement already satisfied: idna<3,>=2.5 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (2.10)

Requirement already satisfied: mpmath>=0.19 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from sympy->torch->groundingdino==0.1.0) (1.3.0)

Requirement already satisfied: six>=1.5 in d:\stablediffusion\.a1sdwebui\py310\lib\site-packages (from python-dateutil>=2.7->matplotlib->supervision==0.6.0->groundingdino==0.1.0) (1.16.0)

Building wheels for collected packages: groundingdino, pycocotools

  Building wheel for groundingdino (setup.py): started

  Building wheel for groundingdino (setup.py): finished with status 'done'

  Created wheel for groundingdino: filename=groundingdino-0.1.0-py3-none-any.whl size=83559 sha256=faaadab5bd5871f26fa5b7ff70ffac432316f4cda3fb28f74692df9def8f8865

  Stored in directory: C:\Users\DELL\AppData\Local\Temp\pip-ephem-wheel-cache-0bbbh64s\wheels\85\2b\15\c5a09de5cf3f52e0609c97c8335f8f40f01d4855e46dfd0e26

  Building wheel for pycocotools (pyproject.toml): started

  Building wheel for pycocotools (pyproject.toml): finished with status 'error'

Successfully built groundingdino

Failed to build pycocotools

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/IDEA-Research/GroundingDINO 'C:\Users\DELL\AppData\Local\Temp\pip-req-build-h4b7ea9k'

  error: subprocess-exited-with-error

  × Building wheel for pycocotools (pyproject.toml) did not run successfully.

  │ exit code: 1

  ╰─> [23 lines of output]

      running bdist_wheel

      running build

      running build_py

      creating build

      creating build\lib.win-amd64-cpython-310

      creating build\lib.win-amd64-cpython-310\pycocotools

      copying pycocotools\coco.py -> build\lib.win-amd64-cpython-310\pycocotools

      copying pycocotools\cocoeval.py -> build\lib.win-amd64-cpython-310\pycocotools

      copying pycocotools\mask.py -> build\lib.win-amd64-cpython-310\pycocotools

      copying pycocotools\__init__.py -> build\lib.win-amd64-cpython-310\pycocotools

      running build_ext

      building 'pycocotools._mask' extension

      creating build\temp.win-amd64-cpython-310

      creating build\temp.win-amd64-cpython-310\Release

      creating build\temp.win-amd64-cpython-310\Release\common

      creating build\temp.win-amd64-cpython-310\Release\pycocotools
None

GroundingDINO install failed. Please submit an issue to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues.
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\stablediffusion\.A1SDWEBUI\py310\lib\site-packages\numpy\core\include -I./common -ID:\stablediffusion\.A1SDWEBUI\py310\include -ID:\stablediffusion\.A1SDWEBUI\py310\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /Tc./common/maskApi.c /Fobuild\temp.win-amd64-cpython-310\Release\./common/maskApi.obj

      maskApi.c

      ./common/maskApi.c(151): warning C4101: \xa1\xb0xp\xa1\xb1: δ\xd2\xfd\xd3õľֲ\xbf\xb1\xe4\xc1\xbf

      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\stablediffusion\.A1SDWEBUI\py310\lib\site-packages\numpy\core\include -I./common -ID:\stablediffusion\.A1SDWEBUI\py310\include -ID:\stablediffusion\.A1SDWEBUI\py310\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-cpython-310\Release\pycocotools/_mask.obj

      _mask.c

      c1: fatal error C1083: \xce޷\xa8\xb4\xf2\xbf\xaaԴ\xceļ\xfe: \xa1\xb0pycocotools/_mask.c\xa1\xb1: No such file or directory

      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

  ERROR: Failed building wheel for pycocotools

ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects

**Comment by ziwenzrs** [comment]
我遇到的问题和你一模一样，不知道是什么原因导致的。用的是整合包V4

**Comment by anurnomeru** [comment]
+1

**Comment by xiongbb** [comment]
+1,秋叶整合包
