### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Loser02** [IDEA-Research/Grounded-Segment-Anything#228]
None
GroundingDINO install failed. Please submit an issue to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues.
Initializing SAM
Running SAM Inference (480, 854, 3)
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\ai\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\sam.py", line 209, in sam_predict
    if dino_enabled and boxes_filt.shape[0] > 1:
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by rentainhe** [comment]
It seems there's no box to be detected, you can try another prompt for detection

**Comment by Loser02** [comment]
wdym by box?

**Comment by rentainhe** [comment]
> wdym by box?

> if dino_enabled and boxes_filt.shape[0] > 1:
AttributeError: 'NoneType' object has no attribute 'shape'

It seems `boxes_filt` is None, which means there may be no box to be detected by your prompt
