### ISSUE TITLE
ModuleNotFoundError: No module named '_socket'

### ISSUE THREAD

**Issue by huyunan496** [IDEA-Research/Grounded-Segment-Anything#234]
first use GroundingDINO：

Command: "D:\sd-webui-aki\sd-webui-aki-v4\py310\python.exe" -m pip install git+https://github.com/IDEA-Research/GroundingDINO --prefer-binary --index-url https://mirrors.bfsu.edu.cn/pypi/web/simple
Error code: 2
stdout: Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple, https://pypi.tuna.tsinghua.edu.cn/simple, https://pypi.doubanio.com/simple

Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html

Collecting git+https://github.com/IDEA-Research/GroundingDINO

  Cloning https://github.com/IDEA-Research/GroundingDINO to c:\users\user\appdata\local\temp\pip-req-build-aiy84e96

  Resolved https://github.com/IDEA-Research/GroundingDINO to commit 67bb0b634a1de07f3581e55d158f3f48dd1e8d05

  Preparing metadata (setup.py): started

  Preparing metadata (setup.py): finished with status 'done'

Requirement already satisfied: torch in d:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages (from groundingdino==0.1.0) (2.0.0+cu118)

Requirement already satisfied: torchvision in d:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages (from groundingdino==0.1.0) (0.15.1+cu118)

Requirement already satisfied: transformers in d:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages (from groundingdino==0.1.0) (4.25.1)

Requirement already satisfied: addict in d:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages (from groundingdino==0.1.0) (2.4.0)

Requirement already satisfied: yapf in d:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages (from groundingdino==0.1.0) (0.32.0)

Requirement already satisfied: timm in d:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages (from groundingdino==0.1.0) (0.6.7)

Requirement already satisfied: numpy in d:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages (from groundingdino==0.1.0) (1.23.3)

Requirement already satisfied: opencv-python in d:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages (from groundingdino==0.1.0) (4.7.0.72)

Collecting supervision==0.6.0

  Using cached https://pypi.doubanio.com/packages/42/7a/4fe657cae29eedeca34756a80a053ac3b1b3c80462cdb6768f428625f9ca/supervision-0.6.0-py3-none-any.whl (31 kB)

Collecting pycocotools

  Downloading https://pypi.doubanio.com/packages/ef/c6/90220be3b39fbc4cbd203775ca47dd8dc97fae06fbd2b500637395621b7c/pycocotools-2.0.6.tar.gz (24 kB)

  Installing build dependencies: started

  Installing build dependencies: finished with status 'done'

  Getting requirements to build wheel: started

  Getting requirements to build wheel: finished with status 'done'

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/IDEA-Research/GroundingDINO 'C:\Users\user\AppData\Local\Temp\pip-req-build-aiy84e96'

ERROR: Exception:

Traceback (most recent call last):

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper

    status = run_func(*args)

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper

    return func(self, options, args)

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\commands\install.py", line 419, in run

    requirement_set = resolver.resolve(

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve

    result = self._result = resolver.resolve(

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve

    state = resolution.resolve(requirements, max_rounds=max_rounds)

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 373, in resolve

    failure_causes = self._attempt_to_pin_criterion(name)

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 213, in _attempt_to_pin_criterion

    criteria = self._get_updated_criteria(candidate)

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 204, in _get_updated_criteria

    self._add_to_criteria(criteria, requirement, parent=candidate)

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria

    if not criterion.candidates:

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__

    return bool(self._sequence)

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__

    return any(self)

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>

    return (c for c in iterator if id(c) not in self._incompatible_ids)

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built

    candidate = func()

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link

    self._link_candidate_cache[link] = LinkCandidate(

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__

    super().__init__(

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__

    self.dist = self._prepare()

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare

    dist = self._prepare_distribution()

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution

    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\operations\prepare.py", line 491, in prepare_linked_requirement

    return self._prepare_linked_requirement(req, parallel_builds)

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\operations\prepare.py", line 577, in _prepare_linked_requirement

    dist = _get_prepared_distribution(

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\operations\prepare.py", line 69, in _get_prepared_distribution

    abstract_dist.prepare_distribution_metadata(

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\distributions\sdist.py", line 48, in prepare_distribution_metadata

    self._install_build_reqs(finder)

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\distributions\sdist.py", line 118, in _install_build_reqs

    build_reqs = self._get_build_requires_wheel()

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\distributions\sdist.py", line 95, in _get_build_requires_wheel

    return backend.get_requires_for_build_wheel()

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_internal\utils\misc.py", line 701, in get_requires_for_build_wheel

    return super().get_requires_for_build_wheel(config_settings=cs)

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel

    return self._call_hook('get_requires_for_build_wheel', {

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook

    raise BackendUnavailable(data.get('traceback', ''))

pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):

  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend

    obj = import_module(mod_path)

  File "importlib\__init__.py", line 126, in import_module

  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 883, in exec_module

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "C:\Users\user\AppData\Local\Temp\pip-build-env-xg00altj\overlay\Lib\site-packages\setuptools\__init__.py", line 15, in <module>

    import setuptools.version

  File "C:\Users\user\AppData\Local\Temp\pip-build-env-xg00altj\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>

    from ._importlib import metadata

  File "C:\Users\user\AppData\Local\Temp\pip-build-env-xg00altj\overlay\Lib\site-packages\setuptools\_importlib.py", line 44, in <module>

    import importlib.metadata as metadata  # noqa: F401

  File "importlib\metadata\__init__.py", line 17, in <module>

  File "importlib\metadata\_adapters.py", line 3, in <module>

  File "email\message.py", line 15, in <module>

  File "email\utils.py", line 29, in <module>

None
  File "socket.py", line 51, in <module>

GroundingDINO install failed. Please submit an issue to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues.
ModuleNotFoundError: No module named '_socket'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by rentainhe** [comment]
Maybe there are some incompatible python package or version for this, you should check if there're some package need to be updated or not
