### ISSUE TITLE
秋叶整合包报错Running GroundingDINO Inference RuntimeError: shape '[30522, 768]' is invalid for input of size 2822882

### ISSUE THREAD

**Issue by XiaoCC** [IDEA-Research/Grounded-Segment-Anything#246]
秋叶整合包报错请问下要怎么修复 调试了2天了还没弄好
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinT_OGC (694MB)
final text_encoder_type: bert-base-uncased
Traceback (most recent call last):
File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 394, in run_predict
output = await app.get_blocks().process_api(
File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1075, in process_api
result = await self.call_function(
File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 884, in call_function
prediction = await anyio.to_thread.run_sync(
File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
return await get_asynclib().run_sync_in_worker_thread(
File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio_backends_asyncio.py", line 937, in run_sync_in_worker_thread
return await future
File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio_backends_asyncio.py", line 867, in run
result = context.run(func, *args)
File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\sam.py", line 248, in dino_predict
boxes_filt, install_success = dino_predict_internal(input_image, dino_model_name, text_prompt, box_threshold)
File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 136, in dino_predict_internal
dino_model = load_dino_model(dino_model_name)
File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 83, in load_dino_model
dino = build_model(args)
File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models_init_.py", line 17, in build_model
model = build_func(args)
File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 372, in build_groundingdino
model = GroundingDINO(
File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 108, in init
self.bert = get_tokenlizer.get_pretrained_language_model(text_encoder_type)
File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\util\get_tokenlizer.py", line 23, in get_pretrained_language_model
return BertModel.from_pretrained(text_encoder_type)
File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\modeling_utils.py", line 2301, in from_pretrained
state_dict = load_state_dict(resolved_archive_file)
File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\modeling_utils.py", line 413, in load_state_dict
return safe_load_file(checkpoint_file)
File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\safetensors\torch.py", line 101, in load_file
result[k] = f.get_tensor(k)
RuntimeError: shape '[30522, 768]' is invalid for input of size 2822882
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by XiaoCC** [comment]
python: 3.10.11
 • 
torch: 2.0.0+cu118
 • 
xformers: 0.0.17
 • 
gradio: 3.23.0
 •

**Comment by rentainhe** [comment]
您好，方便分享一下秋叶整合包的具体位置吗

**Comment by XiaoCC** [comment]
D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4

**Comment by XiaoCC** [comment]
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinT_OGC (694MB)
2023-05-10 20:10:35,716 - cmd.py [line:540] - INFO: Ignored error after process had died: OSError(9, '句柄无效。', None, 6, None)
2023-05-10 20:10:35,716 - cmd.py [line:553] - INFO: Ignored error after process had died: OSError(9, '句柄无效。', None, 6, None)
2023-05-10 20:10:35,716 - cmd.py [line:540] - INFO: Ignored error after process had died: OSError(9, '句柄无效。', None, 6, None)
2023-05-10 20:10:35,716 - cmd.py [line:553] - INFO: Ignored error after process had died: OSError(9, '句柄无效。', None, 6, None)
final text_encoder_type: bert-base-uncased
Traceback (most recent call last):
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\sam.py", line 248, in dino_predict
    boxes_filt, install_success = dino_predict_internal(input_image, dino_model_name, text_prompt, box_threshold)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 136, in dino_predict_internal
    dino_model = load_dino_model(dino_model_name)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 83, in load_dino_model
    dino = build_model(args)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\__init__.py", line 17, in build_model
    model = build_func(args)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 372, in build_groundingdino
    model = GroundingDINO(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 108, in __init__
    self.bert = get_tokenlizer.get_pretrained_language_model(text_encoder_type)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\util\get_tokenlizer.py", line 23, in get_pretrained_language_model
    return BertModel.from_pretrained(text_encoder_type)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\modeling_utils.py", line 2301, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\modeling_utils.py", line 402, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

**Comment by XiaoCC** [comment]
<img width="1302" alt="1" src="https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/7299222/ad75fc00-a207-45ab-b4d3-0312b6b93184">
<img width="1290" alt="2" src="https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/7299222/5f010cb6-1a97-4674-b960-7e3f73e8f57e">
<img width="1697" alt="未命名" src="https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/7299222/01266d93-d5ba-433d-934e-ca05a303b2fe">

**Comment by XiaoCC** [comment]
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinT_OGC (694MB)
final text_encoder_type: bert-base-uncased
Traceback (most recent call last):
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\sam.py", line 248, in dino_predict
    boxes_filt, install_success = dino_predict_internal(input_image, dino_model_name, text_prompt, box_threshold)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 136, in dino_predict_internal
    dino_model = load_dino_model(dino_model_name)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 83, in load_dino_model
    dino = build_model(args)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\__init__.py", line 17, in build_model
    model = build_func(args)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 372, in build_groundingdino
    model = GroundingDINO(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 108, in __init__
    self.bert = get_tokenlizer.get_pretrained_language_model(text_encoder_type)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\util\get_tokenlizer.py", line 23, in get_pretrained_language_model
    return BertModel.from_pretrained(text_encoder_type)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\modeling_utils.py", line 2301, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\modeling_utils.py", line 402, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinT_OGC (694MB)
final text_encoder_type: bert-base-uncased
Traceback (most recent call last):
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\sam.py", line 248, in dino_predict
    boxes_filt, install_success = dino_predict_internal(input_image, dino_model_name, text_prompt, box_threshold)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 136, in dino_predict_internal
    dino_model = load_dino_model(dino_model_name)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 83, in load_dino_model
    dino = build_model(args)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\__init__.py", line 17, in build_model
    model = build_func(args)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 372, in build_groundingdino
    model = GroundingDINO(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 108, in __init__
    self.bert = get_tokenlizer.get_pretrained_language_model(text_encoder_type)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\util\get_tokenlizer.py", line 23, in get_pretrained_language_model
    return BertModel.from_pretrained(text_encoder_type)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\modeling_utils.py", line 2301, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\modeling_utils.py", line 402, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinT_OGC (694MB)
final text_encoder_type: bert-base-uncased
Traceback (most recent call last):
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\sam.py", line 248, in dino_predict
    boxes_filt, install_success = dino_predict_internal(input_image, dino_model_name, text_prompt, box_threshold)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 136, in dino_predict_internal
    dino_model = load_dino_model(dino_model_name)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 83, in load_dino_model
    dino = build_model(args)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\__init__.py", line 17, in build_model
    model = build_func(args)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 372, in build_groundingdino
    model = GroundingDINO(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 108, in __init__
    self.bert = get_tokenlizer.get_pretrained_language_model(text_encoder_type)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\util\get_tokenlizer.py", line 23, in get_pretrained_language_model
    return BertModel.from_pretrained(text_encoder_type)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\modeling_utils.py", line 2301, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\modeling_utils.py", line 402, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinB (938MB)
final text_encoder_type: bert-base-uncased
Traceback (most recent call last):
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/config.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\sam.py", line 248, in dino_predict
    boxes_filt, install_success = dino_predict_internal(input_image, dino_model_name, text_prompt, box_threshold)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 136, in dino_predict_internal
    dino_model = load_dino_model(dino_model_name)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 83, in load_dino_model
    dino = build_model(args)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\__init__.py", line 17, in build_model
    model = build_func(args)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 372, in build_groundingdino
    model = GroundingDINO(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 108, in __init__
    self.bert = get_tokenlizer.get_pretrained_language_model(text_encoder_type)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\util\get_tokenlizer.py", line 23, in get_pretrained_language_model
    return BertModel.from_pretrained(text_encoder_type)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\modeling_utils.py", line 2079, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\configuration_utils.py", line 538, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\configuration_utils.py", line 565, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\configuration_utils.py", line 620, in _get_config_dict
    resolved_config_file = cached_file(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\file_download.py", line 1166, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\file_download.py", line 1498, in get_hf_file_metadata
    r = _request_wrapper(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\file_download.py", line 407, in _request_wrapper
    response = _request_wrapper(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\file_download.py", line 442, in _request_wrapper
    return http_backoff(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\utils\_http.py", line 129, in http_backoff
    response = requests.request(method=method, url=url, **kwargs)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/config.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))

**Comment by rentainhe** [comment]
> requests.exceptions.SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/config.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))

这边不太确定是否能登录上Huggingface

**Comment by XiaoCC** [comment]
原来是bert-base-uncased的模型下载不完整导致的，清除缓存重新下载就好了
