### ISSUE TITLE
 Error checking compiler version for cl: [WinError 2]

### ISSUE THREAD

**Issue by pzzmyc** [IDEA-Research/Grounded-Segment-Anything#267]
Installing sd-webui-segment-anything requirement: groundingdino
Traceback (most recent call last):
  File "A:\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\dino.py", line 36, in install_goundingdino
    launch.run_pip(
  File "A:\stable-diffusion-webui\launch.py", line 129, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "A:\stable-diffusion-webui\launch.py", line 97, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install sd-webui-segment-anything requirement: groundingdino.
Command: "A:\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install git+https://github.com/IDEA-Research/GroundingDINO --prefer-binary
Error code: 1
stdout: Collecting git+https://github.com/IDEA-Research/GroundingDINO
  Cloning https://github.com/IDEA-Research/GroundingDINO to c:\users\administrator\appdata\local\temp\pip-req-build-ubfzo9iu

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/IDEA-Research/GroundingDINO 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-ubfzo9iu'
  fatal: unable to access 'https://github.com/IDEA-Research/GroundingDINO/': Failed to connect to 127.0.0.1 port 2336 after 2055 ms: Couldn't connect to server
  error: subprocess-exited-with-error

  git clone --filter=blob:none --quiet https://github.com/IDEA-Research/GroundingDINO 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-ubfzo9iu' did not run successfully.
  exit code: 128

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

git clone --filter=blob:none --quiet https://github.com/IDEA-Research/GroundingDINO 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-ubfzo9iu' did not run successfully.
exit code: 128

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: A:\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip

None
GroundingDINO install failed. Please submit an issue to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues.
Start SAM Processing
Installing sd-webui-segment-anything requirement: groundingdino
Traceback (most recent call last):
  File "A:\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\dino.py", line 36, in install_goundingdino
    launch.run_pip(
  File "A:\stable-diffusion-webui\launch.py", line 129, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "A:\stable-diffusion-webui\launch.py", line 97, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install sd-webui-segment-anything requirement: groundingdino.
Command: "A:\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install git+https://github.com/IDEA-Research/GroundingDINO --prefer-binary
Error code: 1
stdout: Collecting git+https://github.com/IDEA-Research/GroundingDINO
  Cloning https://github.com/IDEA-Research/GroundingDINO to c:\users\administrator\appdata\local\temp\pip-req-build-7id8g1jz
  Resolved https://github.com/IDEA-Research/GroundingDINO to commit 39b1472457b8264adc8581d354bb1d1956ec7ee7
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: torch in a:\stable-diffusion-webui\venv\lib\site-packages (from groundingdino==0.1.0) (2.0.0+cu118)
Requirement already satisfied: torchvision in a:\stable-diffusion-webui\venv\lib\site-packages (from groundingdino==0.1.0) (0.15.1+cu118)
Requirement already satisfied: transformers in a:\stable-diffusion-webui\venv\lib\site-packages (from groundingdino==0.1.0) (4.26.1)
Requirement already satisfied: addict in a:\stable-diffusion-webui\venv\lib\site-packages (from groundingdino==0.1.0) (2.4.0)
Requirement already satisfied: yapf in a:\stable-diffusion-webui\venv\lib\site-packages (from groundingdino==0.1.0) (0.33.0)
Requirement already satisfied: timm in a:\stable-diffusion-webui\venv\lib\site-packages (from groundingdino==0.1.0) (0.6.7)
Requirement already satisfied: numpy in a:\stable-diffusion-webui\venv\lib\site-packages (from groundingdino==0.1.0) (1.23.3)
Requirement already satisfied: opencv-python in a:\stable-diffusion-webui\venv\lib\site-packages (from groundingdino==0.1.0) (4.7.0.72)
Requirement already satisfied: supervision==0.6.0 in a:\stable-diffusion-webui\venv\lib\site-packages (from groundingdino==0.1.0) (0.6.0)
Requirement already satisfied: pycocotools in a:\stable-diffusion-webui\venv\lib\site-packages (from groundingdino==0.1.0) (2.0.6)
Requirement already satisfied: matplotlib in a:\stable-diffusion-webui\venv\lib\site-packages (from supervision==0.6.0->groundingdino==0.1.0) (3.7.1)
Requirement already satisfied: filelock in a:\stable-diffusion-webui\venv\lib\site-packages (from torch->groundingdino==0.1.0) (3.12.0)
Requirement already satisfied: networkx in a:\stable-diffusion-webui\venv\lib\site-packages (from torch->groundingdino==0.1.0) (3.1)
Requirement already satisfied: jinja2 in a:\stable-diffusion-webui\venv\lib\site-packages (from torch->groundingdino==0.1.0) (3.1.2)
Requirement already satisfied: typing-extensions in a:\stable-diffusion-webui\venv\lib\site-packages (from torch->groundingdino==0.1.0) (4.5.0)
Requirement already satisfied: sympy in a:\stable-diffusion-webui\venv\lib\site-packages (from torch->groundingdino==0.1.0) (1.11.1)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in a:\stable-diffusion-webui\venv\lib\site-packages (from torchvision->groundingdino==0.1.0) (9.4.0)
Requirement already satisfied: requests in a:\stable-diffusion-webui\venv\lib\site-packages (from torchvision->groundingdino==0.1.0) (2.30.0)
Requirement already satisfied: regex!=2019.12.17 in a:\stable-diffusion-webui\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (2023.3.23)
Requirement already satisfied: pyyaml>=5.1 in a:\stable-diffusion-webui\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (6.0)
Requirement already satisfied: packaging>=20.0 in a:\stable-diffusion-webui\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (23.1)
Requirement already satisfied: tqdm>=4.27 in a:\stable-diffusion-webui\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (4.64.1)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in a:\stable-diffusion-webui\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (0.13.3)
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in a:\stable-diffusion-webui\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (0.14.1)
Requirement already satisfied: tomli>=2.0.1 in a:\stable-diffusion-webui\venv\lib\site-packages (from yapf->groundingdino==0.1.0) (2.0.1)
Requirement already satisfied: fsspec in a:\stable-diffusion-webui\venv\lib\site-packages (from huggingface-hub<1.0,>=0.11.0->transformers->groundingdino==0.1.0) (2023.4.0)
Requirement already satisfied: fonttools>=4.22.0 in a:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in a:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (1.4.4)
Requirement already satisfied: python-dateutil>=2.7 in a:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (2.8.2)
Requirement already satisfied: pyparsing>=2.3.1 in a:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in a:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (1.0.7)
Requirement already satisfied: cycler>=0.10 in a:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (0.11.0)
Requirement already satisfied: colorama in a:\stable-diffusion-webui\venv\lib\site-packages (from tqdm>=4.27->transformers->groundingdino==0.1.0) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in a:\stable-diffusion-webui\venv\lib\site-packages (from jinja2->torch->groundingdino==0.1.0) (2.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in a:\stable-diffusion-webui\venv\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (3.1.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in a:\stable-diffusion-webui\venv\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (1.26.15)
Requirement already satisfied: idna<4,>=2.5 in a:\stable-diffusion-webui\venv\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in a:\stable-diffusion-webui\venv\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (2022.12.7)
Requirement already satisfied: mpmath>=0.19 in a:\stable-diffusion-webui\venv\lib\site-packages (from sympy->torch->groundingdino==0.1.0) (1.3.0)
Requirement already satisfied: six>=1.5 in a:\stable-diffusion-webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->supervision==0.6.0->groundingdino==0.1.0) (1.16.0)
Building wheels for collected packages: groundingdino
  Building wheel for groundingdino (setup.py): started
  Building wheel for groundingdino (setup.py): finished with status 'error'
  Running setup.py clean for groundingdino
Failed to build groundingdino
Installing collected packages: groundingdino
  Running setup.py install for groundingdino: started
  Running setup.py install for groundingdino: finished with status 'error'

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/IDEA-Research/GroundingDINO 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-7id8g1jz'
  error: subprocess-exited-with-error

  python setup.py bdist_wheel did not run successfully.
  exit code: 1

  [51 lines of output]
  Building wheel groundingdino-0.1.0
  Compiling with CUDA
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-310
  creating build\lib.win-amd64-cpython-310\groundingdino
  copying groundingdino\version.py -> build\lib.win-amd64-cpython-310\groundingdino
  copying groundingdino\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino
  creating build\lib.win-amd64-cpython-310\groundingdino\config
  copying groundingdino\config\GroundingDINO_SwinB_cfg.py -> build\lib.win-amd64-cpython-310\groundingdino\config
  copying groundingdino\config\GroundingDINO_SwinT_OGC.py -> build\lib.win-amd64-cpython-310\groundingdino\config
  copying groundingdino\config\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\config
  creating build\lib.win-amd64-cpython-310\groundingdino\datasets
  copying groundingdino\datasets\transforms.py -> build\lib.win-amd64-cpython-310\groundingdino\datasets
  copying groundingdino\datasets\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\datasets
  creating build\lib.win-amd64-cpython-310\groundingdino\models
  copying groundingdino\models\registry.py -> build\lib.win-amd64-cpython-310\groundingdino\models
  copying groundingdino\models\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\models
  creating build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\box_ops.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\get_tokenlizer.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\inference.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\logger.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\misc.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\slconfig.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\slio.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\time_counter.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\utils.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\visualizer.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\vl_utils.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  creating build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\bertwarper.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\fuse_modules.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\groundingdino.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\ms_deform_attn.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\transformer.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\transformer_vanilla.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\utils.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  creating build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  copying groundingdino\models\GroundingDINO\backbone\backbone.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  copying groundingdino\models\GroundingDINO\backbone\position_encoding.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  copying groundingdino\models\GroundingDINO\backbone\swin_transformer.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  copying groundingdino\models\GroundingDINO\backbone\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  running build_ext
  A:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] ϵͳҲָļ
    warnings.warn(f'Error checking compiler version for {compiler}: {error}')
  error: [WinError 2] ϵͳҲָļ
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for groundingdino
  error: subprocess-exited-with-error

  Running setup.py install for groundingdino did not run successfully.
  exit code: 1

  [53 lines of output]
  Building wheel groundingdino-0.1.0
  Compiling with CUDA
  running install
  A:\stable-diffusion-webui\venv\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-310
  creating build\lib.win-amd64-cpython-310\groundingdino
  copying groundingdino\version.py -> build\lib.win-amd64-cpython-310\groundingdino
  copying groundingdino\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino
  creating build\lib.win-amd64-cpython-310\groundingdino\config
  copying groundingdino\config\GroundingDINO_SwinB_cfg.py -> build\lib.win-amd64-cpython-310\groundingdino\config
  copying groundingdino\config\GroundingDINO_SwinT_OGC.py -> build\lib.win-amd64-cpython-310\groundingdino\config
  copying groundingdino\config\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\config
  creating build\lib.win-amd64-cpython-310\groundingdino\datasets
  copying groundingdino\datasets\transforms.py -> build\lib.win-amd64-cpython-310\groundingdino\datasets
  copying groundingdino\datasets\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\datasets
  creating build\lib.win-amd64-cpython-310\groundingdino\models
  copying groundingdino\models\registry.py -> build\lib.win-amd64-cpython-310\groundingdino\models
  copying groundingdino\models\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\models
  creating build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\box_ops.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\get_tokenlizer.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\inference.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\logger.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\misc.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\slconfig.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\slio.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\time_counter.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\utils.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\visualizer.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\vl_utils.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  creating build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\bertwarper.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\fuse_modules.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\groundingdino.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\ms_deform_attn.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\transformer.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\transformer_vanilla.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\utils.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  creating build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  copying groundingdino\models\GroundingDINO\backbone\backbone.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  copying groundingdino\models\GroundingDINO\backbone\position_encoding.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  copying groundingdino\models\GroundingDINO\backbone\swin_transformer.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  copying groundingdino\models\GroundingDINO\backbone\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  running build_ext
  A:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] ϵͳҲָļ
    warnings.warn(f'Error checking compiler version for {compiler}: {error}')
  error: [WinError 2] ϵͳҲָļ
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

Encountered error while trying to install package.

groundingdino

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: A:\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip

None
GroundingDINO install failed. Please submit an issue to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues.

**Comment by ffiras** [comment]
same error

**Comment by woshixty** [comment]
same error
