### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'image_encoder'

### ISSUE THREAD

**Issue by sunyiwk** [IDEA-Research/Grounded-Segment-Anything#271]
Start SAM Processing
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinT_OGC (694MB)
Initializing SAM
Running SAM Inference (767, 545, 3)
Traceback (most recent call last):
  File "D:\STABLE2\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\STABLE2\venv\lib\site-packages\gradio\blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "D:\STABLE2\venv\lib\site-packages\gradio\blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\STABLE2\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\STABLE2\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\STABLE2\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\STABLE2\extensions\sd-webui-segment-anything\scripts\sam.py", line 207, in sam_predict
    predictor = SamPredictor(sam)
  File "D:\STABLE2\venv\lib\site-packages\segment_anything\predictor.py", line 31, in __init__
    self.transform = ResizeLongestSide(sam_model.image_encoder.img_size)
AttributeError: 'NoneType' object has no attribute 'image_encoder'

**Comment by rentainhe** [comment]
> 

Hello, have you initialized SAM model before running this, would you like to perform more information about param `sam_model`

**Comment by fresno808** [comment]
any updates? im getting this error too

**Comment by alisson-anjos** [comment]
solution for me: https://github.com/storyicon/comfyui_segment_anything/issues/36
