### ISSUE TITLE
[Bug]: Error when installing groundingdino with sd-webui-segment-anything

### ISSUE THREAD

**Issue by shohinrahmonov** [IDEA-Research/Grounded-Segment-Anything#277]
I get the following error:
```
Installing sd-webui-segment-anything requirement: groundingdino
Traceback (most recent call last):
  File "/workspace/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/dino.py", line 36, in install_goundingdino
    launch.run_pip(
  File "/workspace/stable-diffusion-webui/launch.py", line 143, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
  File "/workspace/stable-diffusion-webui/launch.py", line 111, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install sd-webui-segment-anything requirement: groundingdino.
Command: "/workspace/stable-diffusion-webui/venv/bin/python3" -m pip install git+https://github.com/IDEA-Research/GroundingDINO --prefer-binary
Error code: 1
stdout: Collecting git+https://github.com/IDEA-Research/GroundingDINO
  Cloning https://github.com/IDEA-Research/GroundingDINO to /tmp/pip-req-build-9lpqvgu2
  Resolved https://github.com/IDEA-Research/GroundingDINO to commit 31aa788a3cf6ab82d27385f39e242b34af9cc011
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: addict in ./venv/lib/python3.10/site-packages (from groundingdino==0.1.0) (2.4.0)
Requirement already satisfied: numpy in ./venv/lib/python3.10/site-packages (from groundingdino==0.1.0) (1.23.5)
Requirement already satisfied: opencv-python in ./venv/lib/python3.10/site-packages (from groundingdino==0.1.0) (4.7.0.68)
Collecting pycocotools
  Downloading pycocotools-2.0.6.tar.gz (24 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting supervision==0.6.0
  Downloading supervision-0.6.0-py3-none-any.whl (31 kB)
Requirement already satisfied: timm in ./venv/lib/python3.10/site-packages (from groundingdino==0.1.0) (0.6.7)
Requirement already satisfied: torch in ./venv/lib/python3.10/site-packages (from groundingdino==0.1.0) (1.13.1+cu117)
Requirement already satisfied: torchvision in ./venv/lib/python3.10/site-packages (from groundingdino==0.1.0) (0.14.1+cu117)
Requirement already satisfied: transformers in ./venv/lib/python3.10/site-packages (from groundingdino==0.1.0) (4.25.1)
Requirement already satisfied: yapf in ./venv/lib/python3.10/site-packages (from groundingdino==0.1.0) (0.32.0)
Requirement already satisfied: matplotlib in ./venv/lib/python3.10/site-packages (from supervision==0.6.0->groundingdino==0.1.0) (3.7.0)
Requirement already satisfied: typing-extensions in ./venv/lib/python3.10/site-packages (from torch->groundingdino==0.1.0) (4.5.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in ./venv/lib/python3.10/site-packages (from torchvision->groundingdino==0.1.0) (9.4.0)
Requirement already satisfied: requests in ./venv/lib/python3.10/site-packages (from torchvision->groundingdino==0.1.0) (2.25.1)
Requirement already satisfied: pyyaml>=5.1 in ./venv/lib/python3.10/site-packages (from transformers->groundingdino==0.1.0) (6.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in ./venv/lib/python3.10/site-packages (from transformers->groundingdino==0.1.0) (0.13.2)
Requirement already satisfied: tqdm>=4.27 in ./venv/lib/python3.10/site-packages (from transformers->groundingdino==0.1.0) (4.64.1)
Requirement already satisfied: packaging>=20.0 in ./venv/lib/python3.10/site-packages (from transformers->groundingdino==0.1.0) (23.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.10.0 in ./venv/lib/python3.10/site-packages (from transformers->groundingdino==0.1.0) (0.14.1)
Requirement already satisfied: filelock in ./venv/lib/python3.10/site-packages (from transformers->groundingdino==0.1.0) (3.9.0)
Requirement already satisfied: regex!=2019.12.17 in ./venv/lib/python3.10/site-packages (from transformers->groundingdino==0.1.0) (2022.10.31)
Requirement already satisfied: fsspec in ./venv/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.10.0->transformers->groundingdino==0.1.0) (2023.1.0)
Requirement already satisfied: fonttools>=4.22.0 in ./venv/lib/python3.10/site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (4.38.0)
Requirement already satisfied: cycler>=0.10 in ./venv/lib/python3.10/site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./venv/lib/python3.10/site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (1.4.4)
Requirement already satisfied: pyparsing>=2.3.1 in ./venv/lib/python3.10/site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in ./venv/lib/python3.10/site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (2.8.2)
Requirement already satisfied: contourpy>=1.0.1 in ./venv/lib/python3.10/site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (1.0.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venv/lib/python3.10/site-packages (from requests->torchvision->groundingdino==0.1.0) (1.26.14)
Requirement already satisfied: chardet<5,>=3.0.2 in ./venv/lib/python3.10/site-packages (from requests->torchvision->groundingdino==0.1.0) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in ./venv/lib/python3.10/site-packages (from requests->torchvision->groundingdino==0.1.0) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.10/site-packages (from requests->torchvision->groundingdino==0.1.0) (2022.12.7)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->supervision==0.6.0->groundingdino==0.1.0) (1.16.0)
Building wheels for collected packages: groundingdino, pycocotools
  Building wheel for groundingdino (setup.py): started
  Building wheel for groundingdino (setup.py): finished with status 'done'
  Created wheel for groundingdino: filename=groundingdino-0.1.0-py3-none-any.whl size=84597 sha256=44818d7863839c1ba235b8b217bdd4a2f05164aa683bcc6c61f5c6dd06ea2fbd
  Stored in directory: /tmp/pip-ephem-wheel-cache-lpvjyrnz/wheels/85/2b/15/c5a09de5cf3f52e0609c97c8335f8f40f01d4855e46dfd0e26
  Building wheel for pycocotools (pyproject.toml): started
  Building wheel for pycocotools (pyproject.toml): finished with status 'error'
Successfully built groundingdino
Failed to build pycocotools

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/IDEA-Research/GroundingDINO /tmp/pip-req-build-9lpqvgu2
  error: subprocess-exited-with-error
  
  × Building wheel for pycocotools (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/pycocotools
      copying pycocotools/__init__.py -> build/lib.linux-x86_64-cpython-310/pycocotools
      copying pycocotools/coco.py -> build/lib.linux-x86_64-cpython-310/pycocotools
      copying pycocotools/cocoeval.py -> build/lib.linux-x86_64-cpython-310/pycocotools
      copying pycocotools/mask.py -> build/lib.linux-x86_64-cpython-310/pycocotools
      running build_ext
      cythoning pycocotools/_mask.pyx to pycocotools/_mask.c
      /tmp/pip-build-env-ndbeoo8z/overlay/lib/python3.10/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-6922af9l/pycocotools_20a92dac5ec7471f9c72d573470086c5/pycocotools/_mask.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      building 'pycocotools._mask' extension
      creating build/temp.linux-x86_64-cpython-310
      creating build/temp.linux-x86_64-cpython-310/common
      creating build/temp.linux-x86_64-cpython-310/pycocotools
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/tmp/pip-build-env-ndbeoo8z/overlay/lib/python3.10/site-packages/numpy/core/include -I./common -I/workspace/stable-diffusion-webui/venv/include -I/usr/include/python3.10 -c ./common/maskApi.c -o build/temp.linux-x86_64-cpython-310/./common/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
      error: command 'x86_64-linux-gnu-gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects
```

**Comment by rentainhe** [comment]
> Failed to build pycocotools

maybe you can try to install pycocotools first then install GroundingDINO

**Comment by axonaxis** [comment]
遇到同样的问题，从stackoverflow看到的解决方案
https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory
sudo apt-get install python-dev   # for python2.x installs
sudo apt-get install python3-dev  # for python3.x installs

**Comment by shohinrahmonov** [comment]
> > Failed to build pycocotools
> 
> maybe you can try to install pycocotools first then install GroundingDINO

Thank you. pycocotools somehow wasn't installed
