### ISSUE TITLE
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

### ISSUE THREAD

**Issue by zzh805780186** [IDEA-Research/Grounded-Segment-Anything#287]
**_I wrote the code provided by the author to a file  and  named 'annotate_meself.py' with meself :_**

from groundingdino.util.inference import load_model, load_image, predict, annotate
import cv2

model = load_model("GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py", "./groundingdino_swint_ogc.pth")
IMAGE_PATH = "assets/demo1.jpg"
TEXT_PROMPT = "bear."
BOX_TRESHOLD = 0.35
TEXT_TRESHOLD = 0.25
image_source, image = load_image(IMAGE_PATH)
boxes, logits, phrases = predict(
    model=model,
    image=image,
    caption=TEXT_PROMPT,
    box_threshold=BOX_TRESHOLD,
    text_threshold=TEXT_TRESHOLD
)
annotated_frame = annotate(image_source=image_source, boxes=boxes, logits=logits, phrases=phrases)
cv2.imwrite("annotated_image.jpg", annotated_frame)

_**When I run the code,I encountered the following error：**_

/home/zhaozihao/anaconda3/envs/Grounded-SAM/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
final text_encoder_type: bert-base-uncased
Traceback (most recent call last):
  File "annotate_meself.py", line 4, in <module>
    model = load_model("/home/zhaozihao/FF003/Grounded-SAM/Grounded-Segment-Anything/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py", "/home/zhaozihao/FF003/Grounded-SAM/Grounded-Segment-Anything/groundingdino_swint_ogc.pth")
  File "/home/zhaozihao/FF003/Grounded-SAM/Grounded-Segment-Anything-main/GroundingDINO/groundingdino/util/inference.py", line 31, in load_model
    model = build_model(args)
  File "/home/zhaozihao/FF003/Grounded-SAM/Grounded-Segment-Anything-main/GroundingDINO/groundingdino/models/__init__.py", line 17, in build_model
    model = build_func(args)
  File "/home/zhaozihao/FF003/Grounded-SAM/Grounded-Segment-Anything-main/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 372, in build_groundingdino
    model = GroundingDINO(
  File "/home/zhaozihao/FF003/Grounded-SAM/Grounded-Segment-Anything-main/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 107, in __init__
    self.tokenizer = get_tokenlizer.get_tokenlizer(text_encoder_type)
  File "/home/zhaozihao/FF003/Grounded-SAM/Grounded-Segment-Anything-main/GroundingDINO/groundingdino/util/get_tokenlizer.py", line 17, in get_tokenlizer
    tokenizer = AutoTokenizer.from_pretrained(text_encoder_type)
  File "/home/zhaozihao/anaconda3/envs/Grounded-SAM/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 470, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/home/zhaozihao/anaconda3/envs/Grounded-SAM/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 612, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/zhaozihao/anaconda3/envs/Grounded-SAM/lib/python3.8/site-packages/transformers/configuration_utils.py", line 537, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/zhaozihao/anaconda3/envs/Grounded-SAM/lib/python3.8/site-packages/transformers/configuration_utils.py", line 585, in _get_config_dict
    resolved_config_file = cached_path(
  File "/home/zhaozihao/anaconda3/envs/Grounded-SAM/lib/python3.8/site-packages/transformers/file_utils.py", line 1846, in cached_path
    output_path = get_from_cache(
  File "/home/zhaozihao/anaconda3/envs/Grounded-SAM/lib/python3.8/site-packages/transformers/file_utils.py", line 2102, in get_from_cache
    raise ValueError(
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

**_Who can tell me the reson why?  And how to resolve it?  Thanks_**

**Comment by rentainhe** [comment]
> ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

It seems like there're some errors when connecting to huggingface transformers, maybe you can try it later or try to run the model locally, here're some tips: https://github.com/IDEA-Research/Grounded-Segment-Anything/issues/286#issuecomment-1569531029

**Comment by zzh805780186** [comment]
> > ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.
> 
> It seems like there're some errors when connecting to huggingface transformers, maybe you can try it later or try to run the model locally, here're some tips: [#286 (comment)](https://github.com/IDEA-Research/Grounded-Segment-Anything/issues/286#issuecomment-1569531029)

Good job !  Thanks. 
I successfully ran the demo and was amazed at the project.
