### ISSUE TITLE
download GroundingDino model from huggingface failed. 

### ISSUE THREAD

**Issue by demonsheen** [IDEA-Research/Grounded-Segment-Anything#312]
Found GroundingDINO in pip. Verifying if dynamic library build success.
GroundingDINO dynamic library have been successfully built.
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinT_OGC (694MB)
final text_encoder_type: bert-base-uncased
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\file_download.py", line 1291, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\sam.py", line 247, in dino_predict
    boxes_filt, install_success = dino_predict_internal(input_image, dino_model_name, text_prompt, box_threshold)
  File "D:\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 173, in dino_predict_internal
    dino_model = load_dino_model(dino_model_name, install_success)
  File "D:\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 119, in load_dino_model
    dino = build_model(args)
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\__init__.py", line 17, in build_model
    model = build_func(args)
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 371, in build_groundingdino
    model = GroundingDINO(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 107, in __init__
    self.tokenizer = get_tokenlizer.get_tokenlizer(text_encoder_type)
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\util\get_tokenlizer.py", line 19, in get_tokenlizer
    tokenizer = AutoTokenizer.from_pretrained(text_encoder_type)
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 597, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\transformers\models\auto\configuration_auto.py", line 809, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\transformers\configuration_utils.py", line 559, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\transformers\configuration_utils.py", line 614, in _get_config_dict
    resolved_config_file = cached_file(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\transformers\utils\hub.py", line 443, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bert-base-uncased is not the path to a directory containing a file named config.json.
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by rentainhe** [comment]
Hello, it seems like you did not download the whole files needed for local loading, there should be another config.json in your ckpt path, not only the model.pth

**Comment by rentainhe** [comment]
![image](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/48727989/88286e5c-1baf-4959-8f08-ae498dc97607)

All of these files should be downloaded in your local path

**Comment by demonsheen** [comment]
> ![image](https://user-images.githubusercontent.com/48727989/248140245-88286e5c-1baf-4959-8f08-ae498dc97607.png)
> 
> All of these files should be downloaded in your local path
Thanks for your kindly support,it seems it works! tkstks!!
![groundingDino](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/137272792/4b5bc73b-a83e-4358-9656-08d5c8893500)

**Comment by rentainhe** [comment]
> > ![image](https://user-images.githubusercontent.com/48727989/248140245-88286e5c-1baf-4959-8f08-ae498dc97607.png)
> > All of these files should be downloaded in your local path
> > Thanks for your kindly support,it seems it works! tkstks!!
> > ![groundingDino](https://user-images.githubusercontent.com/137272792/248190605-4b5bc73b-a83e-4358-9656-08d5c8893500.jpg)

You're welcome~

**Comment by littleanapple** [comment]
in docker

**Comment by littleanapple** [comment]
export http_proxy="http://192.168.30.127:4780"
export https_proxy="http://192.168.30.127:4780"

**Comment by TitansWhale** [comment]
> Hello, it seems like you did not download the whole files needed for local loading, there should be another config.json in your ckpt path, not only the model.pth

How can I get to the location in the picture? Where should I go to download the json?
