### ISSUE TITLE
OSError: [Errno 22] 请教一下这个问题是怎么回事呢？秋叶包运行GroundingDINO时偶尔会出现。

### ISSUE THREAD

**Issue by Muziyu888** [IDEA-Research/Grounded-Segment-Anything#316]
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Using local groundingdino.
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinT_OGC (694MB)
final text_encoder_type: bert-base-uncased
Traceback (most recent call last):
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\sam.py", line 247, in dino_predict
    boxes_filt, install_success = dino_predict_internal(input_image, dino_model_name, text_prompt, box_threshold)
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 173, in dino_predict_internal
    dino_model = load_dino_model(dino_model_name, install_success)
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 119, in load_dino_model
    dino = build_model(args)
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\extensions\sd-webui-segment-anything\local_groundingdino\models\__init__.py", line 17, in build_model
    model = build_func(args)
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\extensions\sd-webui-segment-anything\local_groundingdino\models\GroundingDINO\groundingdino.py", line 362, in build_groundingdino
    model = GroundingDINO(
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\extensions\sd-webui-segment-anything\local_groundingdino\models\GroundingDINO\groundingdino.py", line 97, in __init__
    self.tokenizer = get_tokenlizer.get_tokenlizer(text_encoder_type)
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\extensions\sd-webui-segment-anything\local_groundingdino\util\get_tokenlizer.py", line 19, in get_tokenlizer
    tokenizer = AutoTokenizer.from_pretrained(text_encoder_type)
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\py310\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 659, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\py310\lib\site-packages\transformers\tokenization_utils_base.py", line 1760, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\py310\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\file_download.py", line 1302, in hf_hub_download
    with FileLock(lock_path):
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\py310\lib\site-packages\filelock\_api.py", line 255, in __enter__
    self.acquire()
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\py310\lib\site-packages\filelock\_api.py", line 213, in acquire
    self._acquire()
  File "D:\Stable Diffusion\新建文件夹\sd-webui-aki-v4(1)\sd-webui-aki-v4\py310\lib\site-packages\filelock\_windows.py", line 27, in _acquire
    fd = os.open(self.lock_file, flags, self._context.mode)
OSError: [Errno 22] Invalid argument: 'D:\\Stable Diffusion\\新建文件夹\\sd-webui-aki-v4(1)\\sd-webui-aki-v4\\.cache\\huggingface\\hub\\models--bert-base-uncased\\blobs\\W/"949a6f013d67eb8a5b4b5b46026217b888021b88.lock'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by Muziyu888** [comment]
这个GroudingDINO的问题并不是随时都有的，可能10次中有6次会报错，其余4次则可以正常使用，看样子是models--bert-base-uncased这个的问题，但是并不知道该如何解决，求助大佬们，谢谢

**Comment by rentainhe** [comment]
你可以尝试一下把路径换成全英文路径，或者考虑把模型下载下来本地加载

**Comment by Muziyu888** [comment]
现在已经莫名奇妙的好了,我也不知道是什么情况,我做了很多很多的操作,包括下载VS C++,添加环境变量,修改文件路径,以及pip了一堆乱七八糟的东西,也许是其中的某个步骤起到了作用,但是整体是在bilibili上看的教程,并且把大多数教程都走了一遍.
