### ISSUE TITLE
unable install groundingdino

### ISSUE THREAD

**Issue by luck0249** [IDEA-Research/Grounded-Segment-Anything#324]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for groundingdino
  Running setup.py clean for groundingdino
Failed to build groundingdino
ERROR: Could not build wheels for groundingdino, which is required to install pyproject.toml-based projects
Traceback (most recent call last):
  File "D:\novelai-webui-aki-v3\extensions\sd-webui-segment-anything\scripts\dino.py", line 67, in install_goundingdino
GroundingDINO install failed. Will fall back to local groundingdino this time. Please permanently switch to local groundingdino on Settings/Segment Anything or submit an issue to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues.
    launch.run_pip(
Running GroundingDINO Inference
  File "D:\novelai-webui-aki-v3\modules\launch_utils.py", line 130, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)

**Comment by rentainhe** [comment]
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for groundingdino Running setup.py clean for groundingdino Failed to build groundingdino ERROR: Could not build wheels for groundingdino, which is required to install pyproject.toml-based projects Traceback (most recent call last): File "D:\novelai-webui-aki-v3\extensions\sd-webui-segment-anything\scripts\dino.py", line 67, in install_goundingdino GroundingDINO install failed. Will fall back to local groundingdino this time. Please permanently switch to local groundingdino on Settings/Segment Anything or submit an issue to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues. launch.run_pip( Running GroundingDINO Inference File "D:\novelai-webui-aki-v3\modules\launch_utils.py", line 130, in run_pip return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)

1. Check if there're `CUDA_HOME` in your environment, if not, please set it to your CUDA Runtime as `export CUDA_HOME=/path/to/cuda-11.3`
2. Remove the `build` dir and use `pip install -e .` instead of `python setup.py build install`
