### ISSUE TITLE
Found GroundingDINO in pip. Verifying if dynamic library build success. error

### ISSUE THREAD

**Issue by dreamhaxin** [IDEA-Research/Grounded-Segment-Anything#336]
Found GroundingDINO in pip. Verifying if dynamic library build success.
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\dino.py", line 39, in verify_dll
    from groundingdino import _C
ImportError: cannot import name '_C' from 'groundingdino' (C:\stable-diffusion-webui\venv\lib\site-packages\groundingdino\__init__.py)
Failed to build dymanic library. Will uninstall GroundingDINO from pip and re-try installing from GitHub source code. Please permanently switch to local groundingdino on Settings/Segment Anything or submit an issue to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues.
Uninstalling sd-webui-segment-anything requirement: groundingdino
Installing sd-webui-segment-anything requirement: groundingdino
GroundingDINO install success. Verifying if dynamic library build success.
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\dino.py", line 39, in verify_dll
    from groundingdino import _C
ImportError: cannot import name '_C' from 'groundingdino' (C:\stable-diffusion-webui\venv\lib\site-packages\groundingdino\__init__.py)
Failed to build dymanic library. Will uninstall GroundingDINO from pip and fall back to local groundingdino this time. Please permanently switch to local groundingdino on Settings/Segment Anything or submit an issue to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues.
Uninstalling sd-webui-segment-anything requirement: groundingdino
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinB (938MB)
Initializing SAM to cuda
Running SAM Inference (1349, 1080, 3)
SAM inference with 2 boxes, point prompts discarded
Creating output image

**Comment by rentainhe** [comment]
Maybe you can try to install GroundingDINO locally instead of pip install

**Comment by hanxiang1234** [comment]
Running SAM Inference (912, 512, 3)
Start SAM Processing
Found GroundingDINO in pip. Verifying if dynamic library build success.
Failed to build dymanic library. Will uninstall GroundingDINO from pip and re-try installing from GitHub source code. Please permanently switch to local groundingdino on Settings/Segment Anything or submit an issue to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues.
Uninstalling sd-webui-segment-anything requirement: groundingdino
Traceback (most recent call last):
  File "/Users/coco/Documents/ai/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/dino.py", line 39, in verify_dll
    from groundingdino import _C
ImportError: cannot import name '_C' from 'groundingdino' (/opt/homebrew/anaconda3/lib/python3.11/site-packages/groundingdino/__init__.py)
Installing sd-webui-segment-anything requirement: groundingdino
GroundingDINO install success. Verifying if dynamic library build success.
Traceback (most recent call last):
  File "/Users/coco/Documents/ai/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/dino.py", line 39, in verify_dll
    from groundingdino import _C
ImportError: cannot import name '_C' from 'groundingdino' (/opt/homebrew/anaconda3/lib/python3.11/site-packages/groundingdino/__init__.py)
Failed to build dymanic library. Will uninstall GroundingDINO from pip and fall back to local groundingdino this time. Please permanently switch to local groundingdino on Settings/Segment Anything or submit an issue to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues.
Uninstalling sd-webui-segment-anything requirement: groundingdino
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinT_OGC (694MB)
Initializing SAM to mps
Running SAM Inference (912, 512, 3)
