### ISSUE TITLE
The GroundingDINO section encountered an error

### ISSUE THREAD

**Issue by Vio1etovo** [IDEA-Research/Grounded-Segment-Anything#367]
My environment configuration is as follows:

```
Package                  Version      Editable project location
------------------------ ------------ ----------------------------------------------------------
addict                   2.4.0
aiofiles                 22.1.0
aiosqlite                0.19.0
aliyun-python-sdk-core   2.13.36
aliyun-python-sdk-kms    2.16.1
anyio                    3.6.2
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
asttokens                2.2.1
attrs                    23.1.0
Babel                    2.12.1
backcall                 0.2.0
beautifulsoup4           4.12.2
bleach                   6.0.0
certifi                  2023.5.7
cffi                     1.15.1
charset-normalizer       3.1.0
click                    8.1.7
clip                     1.0          /work/home/sam/playground-main/CLIP
cloudpickle              2.1.0
cmake                    3.25.0
colorama                 0.4.6
comm                     0.1.3
contourpy                1.1.0
crcmod                   1.7
cryptography             41.0.3
cycler                   0.11.0
Cython                   0.29.32
cython-bbox              0.1.3
debugpy                  1.6.7
decorator                5.1.1
defusedxml               0.7.1
et-xmlfile               1.1.0
executing                1.2.0
fastjsonschema           2.16.3
filelock                 3.8.0
fonttools                4.36.0
fqdn                     1.5.1
fsspec                   2023.6.0
ftfy                     6.1.1
groundingdino            0.1.0        /work/home/sam/playground-main/GroundingDINO
horovod                  0.25.0
huggingface-hub          0.16.4
idna                     3.4
importlib-metadata       6.8.0
importlib-resources      5.12.0
ipykernel                6.23.0
ipython                  8.12.2
ipython-genutils         0.2.0
isoduration              20.11.0
jedi                     0.18.2
Jinja2                   3.1.2
jmespath                 0.10.0
json5                    0.9.11
jsonpointer              2.3
jsonschema               4.17.3
jupyter_client           8.2.0
jupyter_core             5.3.0
jupyter-events           0.6.3
jupyter_server           2.5.0
jupyter_server_fileid    0.9.0
jupyter_server_terminals 0.4.4
jupyter_server_ydoc      0.8.0
jupyter-ydoc             0.2.4
jupyterlab               3.6.3
jupyterlab-pygments      0.2.2
jupyterlab_server        2.22.1
kiwisolver               1.4.4
lap                      0.4.0
lit                      15.0.7
llvmlite                 0.39.0
Markdown                 3.4.4
markdown-it-py           3.0.0
MarkupSafe               2.1.2
maskrcnn-benchmark       0.0.0        /work/home/sam/playground-main/GLIP
matplotlib               3.7.2
matplotlib-inline        0.1.6
mdurl                    0.1.2
mistune                  2.0.5
mmcv                     2.0.1
mmdet                    3.1.0        /work/home/sam/playground-main/mmdetection
mmengine                 0.8.4
model-index              0.1.11
motmetrics               1.2.5
mpmath                   1.2.1
nbclassic                1.0.0
nbclient                 0.7.4
nbconvert                7.4.0
nbformat                 5.8.0
nest-asyncio             1.5.6
networkx                 3.0
ninja                    1.11.1
notebook                 6.5.4
notebook_shim            0.2.3
numba                    0.56.0
numpy                    1.22.4
opencv-python            4.6.0.66
opencv-python-headless   4.8.0.76
opendatalab              0.0.10
openmim                  0.3.9
openpyxl                 3.0.10
openxlab                 0.0.21
ordered-set              4.1.0
oss2                     2.17.0
packaging                21.3
pandas                   1.4.3
pandocfilters            1.5.0
parso                    0.8.3
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.5.0
pip                      23.2.1
pkgutil_resolve_name     1.3.10
platformdirs             3.5.1
progress                 1.6
prometheus-client        0.16.0
prompt-toolkit           3.0.38
protobuf                 3.20.1
psutil                   5.9.1
ptyprocess               0.7.0
pure-eval                0.2.2
pycocotools              2.0.7
pycparser                2.21
pycryptodome             3.18.0
Pygments                 2.15.1
pyparsing                3.0.9
pyrsistent               0.19.3
python-dateutil          2.8.2
python-json-logger       2.0.7
pytz                     2023.3
PyYAML                   6.0
pyzmq                    25.0.2
regex                    2023.8.8
requests                 2.28.2
rfc3339-validator        0.1.4
rfc3986-validator        0.1.1
rich                     13.4.2
safetensors              0.3.3
scipy                    1.9.0
segment-anything         1.0          /work/home/sam/playground-main/segment-anything
Send2Trash               1.8.2
setuptools               58.2.0
shapely                  2.0.1
six                      1.16.0
sniffio                  1.3.0
soupsieve                2.4.1
stack-data               0.6.2
supervision              0.6.0
sympy                    1.11.1
tabulate                 0.9.0
tensorboardX             2.5.1
termcolor                2.3.0
terminado                0.17.1
terminaltables           3.1.10
timm                     0.9.5
tinycss2                 1.2.1
tokenizers               0.13.3
tomli                    2.0.1
torch                    1.9.0+cu111
torchaudio               0.9.0
torchvision              0.10.0+cu111
tornado                  6.3.1
tqdm                     4.65.2
traitlets                5.9.0
transformers             4.32.1
triton                   2.0.0
typing_extensions        4.3.0
uri-template             1.2.0
urllib3                  1.26.16
wcwidth                  0.2.6
webcolors                1.13
webencodings             0.5.1
websocket-client         1.5.1
wheel                    0.37.1
xmltodict                0.13.0
y-py                     0.5.9
yacs                     0.1.8
yapf                     0.40.1
ypy-websocket            0.8.2
zipp                     3.8.1
```
using GroundingDINO commands ran incorrectly. The error is as follows:

```
root@vscode-1690977852929548290-8588864677-qfmcx:/work/home/sam/playground-main/GroundedSAM# python grounding_dino_demo.py
final text_encoder_type: bert-base-uncased
Traceback (most recent call last):
  File "grounding_dino_demo.py", line 14, in <module>
    model = load_model(CONFIG_PATH, CHECKPOINT_PATH)
  File "/work/home/sam/playground-main/GroundingDINO/groundingdino/util/inference.py", line 32, in load_model
    model = build_model(args)
  File "/work/home/sam/playground-main/GroundingDINO/groundingdino/models/__init__.py", line 17, in build_model
    model = build_func(args)
  File "/work/home/sam/playground-main/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 388, in build_groundingdino
    model = GroundingDINO(
  File "/work/home/sam/playground-main/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 108, in __init__
    self.bert = get_tokenlizer.get_pretrained_language_model(text_encoder_type)
  File "/work/home/sam/playground-main/GroundingDINO/groundingdino/util/get_tokenlizer.py", line 25, in get_pretrained_language_model
    return BertModel.from_pretrained(text_encoder_type)
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 2805, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 469, in load_state_dict
    return safe_load_file(checkpoint_file)
  File "/usr/local/lib/python3.8/dist-packages/safetensors/torch.py", line 310, in load_file
    result[k] = f.get_tensor(k)
AttributeError: module 'torch' has no attribute 'frombuffer'
```
Although you mentioned that `torch>=1.7.0` is supported, I found in the official `torch 1.7.0`~`torch 1.9.0` document that `torch.frombuffer` does not exist, and `torch 2.0.0 does`.

Is it necessary to upgrade to torch 2.0.0?

**Comment by Vio1etovo** [comment]
See [here](https://github.com/huggingface/transformers/issues/25847)

Huggingface's safesensors no longer support versions below `torch 1.10.0`

**Comment by ManOfStory** [comment]
I  met this error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openxlab 0.0.21 requires setuptools~=60.2.0, but you have setuptools 58.2.0 which is incompatible.
```
I wonder how to fix it, thanks.
