### ISSUE TITLE
gradio does not seem to work, version issues ?

### ISSUE THREAD

**Issue by nikste** [IDEA-Research/Grounded-Segment-Anything#392]
running `python gradio_app.py` i get following error:
```
Traceback (most recent call last):
  File "/home/nikste/grounded_sam/scripts/gradio_app.py", line 372, in <module>
    input_image = gr.Image(source='upload', type="pil", value="../assets/demo1.jpg", tool="sketch")
  File "/home/nikste/grounded_sam/venv/lib/python3.10/site-packages/gradio/component_meta.py", line 152, in wrapper
    return fn(self, **kwargs)
TypeError: Image.__init__() got an unexpected keyword argument 'source'
```
The gradio docs confirm that there is no such parameter `source` only `sources`.
Could you publish a working, library pinned `requirements.txt` maybe? (`pip freeze > requirements.txt`)

**Comment by timiil** [comment]
me too, same question here. i am running inside the docker container, pleae give some helps:)

**Comment by crapthings** [comment]
pip install gradio==3.50.2

**Comment by Lin-future** [comment]
> pip install gradio==3.50.2

thx！it works! for me, I used to install version 4.15.
