### ISSUE TITLE
ValueError in Labels issues?

### ISSUE THREAD

**Issue by JohanHuynh0130** [IDEA-Research/Grounded-Segment-Anything#452]
has anyone ever come into the issue below when trying to test other SAM models:
Traceback (most recent call last):
  File "E:\PythonProjects\Grounded-Segment-Anything\EfficientSAM\grounded_mobile_sam.py", line 145, in <module>
    main(args)
  File "E:\PythonProjects\Grounded-Segment-Anything\EfficientSAM\grounded_mobile_sam.py", line 83, in main
    labels = [
  File "E:\PythonProjects\Grounded-Segment-Anything\EfficientSAM\grounded_mobile_sam.py", line 83, in <listcomp>
    labels = [
ValueError: too many values to unpack (expected 5)

Let me know how to fix this please. Thank you!

**Comment by haviduck** [comment]
detections returns 6 values, while the labels list takes into account 5. fixed by changing: 

`labels = [
    f"{CLASSES[class_id]} {confidence:0.2f}" 
    for _, _, confidence, class_id, _
    in detections]`

to: 

`labels = [
    f"{CLASSES[class_id]} {confidence:0.2f}" 
    for _, _, confidence, class_id, _, _
    in detections]`

**Comment by JohanHuynh0130** [comment]
thanks a lot :) @haviduck
