### ISSUE TITLE
ValueError: not enough values to unpack (expected 6, got 4) for grounded_sam_simple_demo.py 

### ISSUE THREAD

**Issue by chuhuan88** [IDEA-Research/Grounded-Segment-Anything#478]
Traceback (most recent call last):
  File "/home/chuhuan/Grounded-Segment-Anything-main/grounded_sam_simple_demo.py", line 51, in <module>
    labels = [
  File "/home/chuhuan/Grounded-Segment-Anything-main/grounded_sam_simple_demo.py", line 53, in <listcomp>
    for _, _, confidence, class_id, _, _ 
ValueError: not enough values to unpack (expected 6, got 4)

**Comment by xhh12381** [comment]
@chuhuan88 The supervision version is too low. I tried updating to the latest version to solve the problem.
pip uninstall supervision
pip install supervision

**Comment by yuanqianxi0503** [comment]
@chuhuan88
labels = [
    f"{CLASSES[class_id]} {confidence:0.2f}"
    for  confidence, class_id
    in zip(detections.confidence, detections.class_id)
]
