### ISSUE TITLE
SSLError: HTTPSConnectionPool(host='huggingface.co', port=443)

### ISSUE THREAD

**Issue by JunDaLee** [IDEA-Research/Grounded-Segment-Anything#52]
I run the demo, and there is an error. How can i figure out it. thanks.
`SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/tokenizer_config.json (Caused by SSLError(SSLZeroReturnError(6, 
'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))`

**Comment by LeanFly** [comment]
maybe you can shutdown your proxy tool

**Comment by JunDaLee** [comment]
thanks. i know shutdown the proxy tool is the direct way, but i don't have the access. i try to download the file to local.

**Comment by JunDaLee** [comment]
i have solved the question,thanks.

**Comment by zhyxun** [comment]
> i have solved the question,thanks.

How did you solve the problem? I have the same problem.

**Comment by JunDaLee** [comment]
you can follow the repo https://zhuanlan.zhihu.com/p/147144376, download the "bert-base-uncased" folder from https://huggingface.co/bert-base-uncased, and modify the error pretrain location to your local position.

**Comment by zhyxun** [comment]
> you can follow the repo https://zhuanlan.zhihu.com/p/147144376, download the "bert-base-uncased" folder from https://huggingface.co/bert-base-uncased, and modify the error pretrain location to your local position.

Thanks very much!

**Comment by dxw2000** [comment]
> you can follow the repo https://zhuanlan.zhihu.com/p/147144376, download the "bert-base-uncased" folder from https://huggingface.co/bert-base-uncased, and modify the error pretrain location to your local position.

I downloaded it locally this way, Will GroundingDINO_SwinT_OGC. Py modify text_encoder_type = "/ MNT/Temp_new DXW/code/AIGC koutu/GroundingDINO/Bert - base - cased", But here's the problem
.. /aten/src/ATen/native/TensorShape.cpp:3483.)
return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
final text_encoder_type: /mnt/Temp_new/dxw/code/AIGC/koutu/GroundingDINO/bert-base-cased
Traceback (most recent call last):
File "/mnt/Temp_new/dxw/code/AIGC/koutu/GroundingDINO/demo/inference_on_a_image.py", line 208, in <module>
model = load_model(config_file, checkpoint_path, cpu_only=args.cpu_only)
File "/mnt/Temp_new/dxw/code/AIGC/koutu/GroundingDINO/demo/inference_on_a_image.py", line 91, in load_model
load_res = model.load_state_dict(clean_state_dict(checkpoint["model"]), strict=False)
The File "/ home/iv/anaconda3 / envs/py39 / lib/python3.9 / site - packages/torch/nn/modules/module. Py", line 2041, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GroundingDINO:
size mismatch for bert.embeddings.word_embeddings.weight:  copying a param with shape torch.Size([30522, 768]) from checkpoint, the shape in current model is torch.Size([28996,  768]).
