### ISSUE TITLE
Can‘t install GroundingDINO in other project

### ISSUE THREAD

**Issue by Cadodo97** [IDEA-Research/Grounded-Segment-Anything#532]
I am using:
- Windows 11
- Torch version: 2.3.0
- Cuda Toolkit version: 11.8
- Python 3.10.11

If a follow [the official guide](https://github.com/IDEA-Research/GroundingDINO/tree/main#:~:text=usr/local/cuda-,Installation%3A,-1.Clone%20the) to install GroundingDINO in a new and empty directory the installation process it's fine and GroundingDINO works.

My probem is when I try to install GroundingDINO as a part of a more complicated project.. I follow the same steps of the Official Repo and the versioning is the same of above.

Printed error is:

    C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\sim_suction_policy\GroundingDINO\groundingdino\models\GroundingDINO\csrc\vision.cpp : fatal error C1083: Non Š possibile aprire il file generato dal compilatore: '': Invalid argument
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\torch\utils\cpp_extension.py", line 1900, in _run_ninja_build
        subprocess.run(
      File "C:\Users\Proprietario\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 526, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\sim_suction_policy\GroundingDINO\setup.py", line 206, in <module>
        setup(
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\setuptools\__init__.py", line 117, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\setuptools\_distutils\core.py", line 183, in setup
        return run_commands(dist)
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\setuptools\_distutils\core.py", line 199, in run_commands
        dist.run_commands()
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\setuptools\_distutils\dist.py", line 954, in run_commands
        self.run_command(cmd)
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\setuptools\dist.py", line 950, in run_command
        super().run_command(command)
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
        cmd_obj.run()
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\setuptools\command\develop.py", line 35, in run
        self.install_for_development()
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\setuptools\command\develop.py", line 112, in install_for_development
        self.run_command('build_ext')
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\setuptools\dist.py", line 950, in run_command
        super().run_command(command)
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
        cmd_obj.run()
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\setuptools\command\build_ext.py", line 98, in run
        _build_ext.run(self)
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
        self.build_extensions()
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\torch\utils\cpp_extension.py", line 843, in build_extensions
        build_ext.build_extensions(self)
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 476, in build_extensions
        self._build_extensions_serial()
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 502, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\setuptools\command\build_ext.py", line 263, in build_extension
        _build_ext.build_extension(self, ext)
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 557, in build_extension
        objects = self.compiler.compile(
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\torch\utils\cpp_extension.py", line 815, in win_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\torch\utils\cpp_extension.py", line 1573, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "C:\Users\Proprietario\Desktop\Donato\python_project\Sim-Suction-API\inference_env\lib\site-packages\torch\utils\cpp_extension.py", line 1916, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    **[end of output]**

This error looks like any other issues, but I follow the same steps used to install GroundingDINO in an empty directory.

Does anyone have any ideas? Will be really appreciated

**Comment by MrMengQi** [comment]
Hi, I'm having the same problem with a similar configuration as you, have you solved it yet?

**Comment by Cadodo97** [comment]
@MrMengQi yes. In my case I was trying to use GroundingDINO in a bigger project.
I solved this issue following these steps:
1. download/create the repository of the project you need
2. create a virtualenv inside this project
3. activate the new virtualenv
4. download groundingDINO outside of the project (Step1)
5. go inside groundingDINO, run: `pip install -e .`
6. go in your main project (Step1)
7. download already groundingdino

the play is done. 
Let me know
