### ISSUE TITLE
ninja: build stopped: subcommand failed

### ISSUE THREAD

**Issue by yier2333** [IDEA-Research/Grounded-Segment-Anything#62]
when i run python -m pip install -e GroundingDINO, i got the error :
   
ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "E:\Project\Grounded-Segment-Anything\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1717, in _run_ninja_build
        subprocess.run(
      File "C:\Users\zhuman\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 512, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
   
    The above exception was the direct cause of the following exception:
   
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "E:\Project\Grounded-Segment-Anything\GroundingDINO\setup.py", line 192, in <module>
        setup(
      File "E:\Project\Grounded-Segment-Anything\venv\lib\site-packages\setuptools\__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "E:\Project\Grounded-Segment-Anything\venv\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
        return run_commands(dist)
      File "E:\Project\Grounded-Segment-Anything\venv\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
        dist.run_commands()
      File "E:\Project\Grounded-Segment-Anything\venv\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
        self.run_command(cmd)
      File "E:\Project\Grounded-Segment-Anything\venv\lib\site-packages\setuptools\dist.py", line 1217, in run_command
        super().run_command(command)
      File "E:\Project\Grounded-Segment-Anything\venv\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
        cmd_obj.run()
      File "E:\Project\Grounded-Segment-Anything\venv\lib\site-packages\setuptools\command\develop.py", line 34, in run
        self.install_for_development()
      File "E:\Project\Grounded-Segment-Anything\venv\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "E:\Project\Grounded-Segment-Anything\venv\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
        self.distribution.run_command(command)
      File "E:\Project\Grounded-Segment-Anything\venv\lib\site-packages\setuptools\dist.py", line 1217, in run_command
        super().run_command(command)
      File "E:\Project\Grounded-Segment-Anything\venv\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
        cmd_obj.run()
      File "E:\Project\Grounded-Segment-Anything\venv\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
        _build_ext.run(self)
      File "E:\Project\Grounded-Segment-Anything\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
        self.build_extensions()
      File "E:\Project\Grounded-Segment-Anything\venv\lib\site-packages\torch\utils\cpp_extension.py", line 735, in build_extensions
        build_ext.build_extensions(self)
      File "E:\Project\Grounded-Segment-Anything\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 466, in build_extensions       
        self._build_extensions_serial()
      File "E:\Project\Grounded-Segment-Anything\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 492, in _build_extensions_seria
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by JAYCHOU2020** [comment]
note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by lizzielss** [comment]
the same issues
