### ISSUE TITLE
ModuleNotFoundError: No module named 'groundingdino'

### ISSUE THREAD

**Issue by souvik0306** [IDEA-Research/Grounded-Segment-Anything#88]
Tried on both Colab and Local Machine. 

Got the same error on both when trying to execute the `grounding_dino_demo.py` file. 

Downloaded the weights file and saved them in the Grounded-Segment-Anything/ directory. 

Is there something else I should know?

**Comment by rentainhe** [comment]
maybe you should try `from GroundingDINO.groundingdino import xxx`, we just did it in a simple way by add GroundingDINO repo under this project, we will modify the code structure for better usage

**Comment by JAYCHOU2020** [comment]
![image](https://user-images.githubusercontent.com/62323435/231353613-3c133f6b-5f19-4437-8da2-15b3b0019c36.png)

> maybe you should try `from GroundingDINO.groundingdino import xxx`, we just did it in a simple way by add GroundingDINO repo under this project, we will modify the code structure for better usage

**Comment by JAYCHOU2020** [comment]
> Tried on both Colab and Local Machine.
> 
> Got the same error on both when trying to execute the `grounding_dino_demo.py` file.
> 
> Downloaded the weights file and saved them in the Grounded-Segment-Anything/ directory.
> 
> Is there something else I should know?

did u fix it

**Comment by souvik0306** [comment]
> > Tried on both Colab and Local Machine.
> > Got the same error on both when trying to execute the `grounding_dino_demo.py` file.
> > Downloaded the weights file and saved them in the Grounded-Segment-Anything/ directory.
> > Is there something else I should know?
> 
> did u fix it

No, not yet. What about you?

**Comment by SlongLiu** [comment]
How about trying this: 

```python
import os, sys
sys.path.append(os.path.join(os.getcwd(), "GroundingDINO"))
```

**Comment by JAYCHOU2020** [comment]
> > > Tried on both Colab and Local Machine.
> > > Got the same error on both when trying to execute the `grounding_dino_demo.py` file.
> > > Downloaded the weights file and saved them in the Grounded-Segment-Anything/ directory.
> > > Is there something else I should know?
> > 
> > 
> > did u fix it
> 
> No, not yet. What about you?



> > > Tried on both Colab and Local Machine.
> > > Got the same error on both when trying to execute the `grounding_dino_demo.py` file.
> > > Downloaded the weights file and saved them in the Grounded-Segment-Anything/ directory.
> > > Is there something else I should know?
> > 
> > 
> > did u fix it
> 
> No, not yet. What about you?

I couldn't compile it even though I recreated other environments

> 

where should i add it

**Comment by JAYCHOU2020** [comment]
> How about trying this:
> 
> ```python
> import os, sys
> sys.path.append(os.path.join(os.getcwd(), "GroundingDINO"))
> ```

where should i add it

**Comment by souvik0306** [comment]
> How about trying this:
> 
> ```python
> import os, sys
> sys.path.append(os.path.join(os.getcwd(), "GroundingDINO"))
> ```

Still got the same error

**Comment by JAYCHOU2020** [comment]
> > How about trying this:
> > ```python
> > import os, sys
> > sys.path.append(os.path.join(os.getcwd(), "GroundingDINO"))
> > ```
> 
> Still got the same error

I stil couldn't compile GroundingDINO even though I recreated other environments

**Comment by betogaona7** [comment]
Besides @SlongLiu code, you may need to add an init file as in #83, you can take a look at Colab in the PR for reference or an as a temporal workaround

**Comment by souvik0306** [comment]
> Besides @SlongLiu code, you may need to add an init file as in #83, you can take a look at Colab in the PR for reference or an as a temporal workaround

Where's the Colab File? Can you please provide a link to it

**Comment by betogaona7** [comment]
https://colab.research.google.com/drive/1TlpjoJ9DBhCXkT4RW_HLswYM6KyySZUh?usp=sharing

**Comment by souvik0306** [comment]
This is the error after 

import os, sys
sys.path.append(os.path.join(os.getcwd(), "GroundingDINO"))

```
Traceback (most recent call last):
  File "/content/Grounded-Segment-Anything/grounding_dino_demo.py", line 8, in <module>
    import GroundingDINO.groundingdino.datasets.transforms as T
  File "/content/Grounded-Segment-Anything/GroundingDINO/groundingdino/datasets/transforms.py", line 13, in <module>
    from groundingdino.util.box_ops import box_xyxy_to_cxcywh
ModuleNotFoundError: No module named 'groundingdino'
```

**Comment by souvik0306** [comment]
> https://colab.research.google.com/drive/1TlpjoJ9DBhCXkT4RW_HLswYM6KyySZUh?usp=sharing - Notice that it will require you to manually add the **init** file described in the PR before the install

So I just need to add the _init__.py under this `GroundingDINO\groundingdino` ?

**Comment by betogaona7** [comment]
> So I just need to add the init_.py under this GroundingDINO\groundingdino ?

No, it should be under `GroundingDINO/groundingdino/datasets/ `, and then you can run the Colab.

**Comment by souvik0306** [comment]
@betogaona7  Tried it, but got this - 
```

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-5-d6d73c840634>](https://localhost:8080/#) in <cell line: 18>()
     16 from GroundingDINO.groundingdino.util.slconfig import SLConfig
     17 from GroundingDINO.groundingdino.util.utils import clean_state_dict, get_phrases_from_posmap
---> 18 from GroundingDINO.groundingdino.util.inference import annotate, load_image, predict
     19 
     20 import supervision as sv

[/content/Grounded-Segment-Anything/GroundingDINO/groundingdino/util/inference.py](https://localhost:8080/#) in <module>
      8 from torchvision.ops import box_convert
      9 
---> 10 import groundingdino.datasets.transforms as T
     11 from groundingdino.models import build_model
     12 from groundingdino.util.misc import clean_state_dict

ModuleNotFoundError: No module named 'groundingdino.datasets'
```

@JAYCHOU2020 were you able to run it?

**Comment by souvik0306** [comment]
@betogaona7 For reference - 
![image](https://user-images.githubusercontent.com/55232104/231359761-0b94007b-559f-4f6c-9baf-e9d3717675ec.png)

**Comment by betogaona7** [comment]
Looks good, did you did the change before installing the packages?, otherwise, it would not work

**Comment by JAYCHOU2020** [comment]
> import os, sys
> sys.path.append(os.path.join(os.getcwd(), "GroundingDINO"))

after i add init.py ,I meet this  error :AttributeError: module 'torch' has no attribute 'frombuffer', and my torch version is 1.10

**Comment by JAYCHOU2020** [comment]
> @betogaona7 For reference - ![image](https://user-images.githubusercontent.com/55232104/231359761-0b94007b-559f-4f6c-9baf-e9d3717675ec.png)

did you work

**Comment by AnasCHARROUD** [comment]
try this 
`%cd /content/GroundingDINO`
if you want to import libraries of GroundingDINO.

**Comment by hehedalulu** [comment]
I also have the question
so sad

**Comment by souvik0306** [comment]
> I also have the question so sad

What's your doubt/error?

**Comment by jerry-mengbo** [comment]
> maybe you should try `from GroundingDINO.groundingdino import xxx`, we just did it in a simple way by add GroundingDINO repo under this project, we will modify the code structure for better usage

so correct

**Comment by littleanapple** [comment]
修复代码引入。
vim /opt/conda/lib/python3.10/site-packages/groundingdino/util/inference.py
import GroundingDINO.groundingdino.datasets.transforms as T
from GroundingDINO.groundingdino.models import build_model
from GroundingDINO.groundingdino.util.misc import clean_state_dict
from GroundingDINO.groundingdino.util.slconfig import SLConfig
from GroundingDINO.groundingdino.util.utils import get_phrases_from_posmap
